### ISSUE TITLE
is it possible to release the source which we can run manually? 

### ISSUE THREAD

**Issue by ruhaise** [CryptoGnome/LimitSwap#1]
now the software doesn't support Linux and mac, before releasing the GUI maybe it makes sense to release the source so that we can manually run the project by installing dependencies and use it early, thanks in advance 👍

**Comment by prashantguleria** [comment]
If he releases the source code, then I don't think that there is any utility of $LIMIT token left.

**Comment by CryptoGnome** [comment]
We are closed source for the time being.
