### ISSUE TITLE
Insufficient Balance. Had 0

### ISSUE THREAD

**Issue by edblak** [CryptoGnome/LimitSwap#10]
the following relates to LimitSwap.Alpha.v2.62.zip 

[errors.log](https://github.com/CryptoGnome/LimitSwap/files/5395188/errors.log)

[terminaloutput.txt](https://github.com/CryptoGnome/LimitSwap/files/5395201/terminaloutput.txt)

[tokens.json.txt](https://github.com/CryptoGnome/LimitSwap/files/5395204/tokens.json.txt)

terminaloutput.txt indicates this issue was generated running the old way through terminal. Note also the tokens.json is the old (no moonbag) layout too.  Then discovered the GUI and running that way with new tokens.json (with moonbag) layout and (first) transaction succeeded. 

seems to be a difference between running through terminal and through GUI - i realise GUI is the way to go forward, but there might be an underlying issue indicated by this behaviour?

see also bug #3 of same title

**Comment by CryptoGnome** [comment]
no the versions have changed, you need to use the latest JSONs with the latest version. This last release will be the last change
