### ISSUE TITLE
add more information in the 1inch log

### ISSUE THREAD

**Issue by ruhaise** [CryptoGnome/LimitSwap#101]
is it possible to add more logging information to the 1inch bot, this can help people who don't use UI a lot. my idea is something like this of course the wordings can be improved this is an example.

-----------------------------------------------------------------------------------------------------------------------------
current token price: 12
buy price: 10 | buy amount: 10 | min base token required for buying now: 120 | min base token required on limit price: 100
sell price: 20 | sell amount: 10 | min base token received if we sell now: 120 | min base token received if sell on limit price: 200
-----------------------------------------------------------------------------------------------------------------------------
 one of the reasons it's good to see these numbers is that sometimes the price will be better in some exchanges but the slippage will be so bad that you will end up getting less. this is a more complicated bot so it's better to see maximum info in the log.

**Comment by CryptoGnome** [comment]
deprecated
