### ISSUE TITLE
Select ETH ou another token as trading par on ping pong

### ISSUE THREAD

**Issue by danielcerdeira** [CryptoGnome/LimitSwap#103]
Select ETH or another token as base Trading par on ping pong.

**Comment by danielcerdeira** [comment]
This topic is related to PING PONG Bot.

Actually this topic is similar to another openned issue but should also be implemented on PING PONG BOT: buy and sell amounts in ETH or select token (https://github.com/CryptoGnome/LimitSwap/issues/91)

The current price, short (sell) and Long (buy) should be calculated based on the trading par (ETH or another selected token) because corrections in ETH can affect the token U$D price even though the trading par (ETH or another selected token) remains constant.

**Comment by CryptoGnome** [comment]
Only USD will be supported
