### ISSUE TITLE
Bug on vwap on pingpong bot

### ISSUE THREAD

**Issue by danielcerdeira** [CryptoGnome/LimitSwap#105]
If a token does not receive any transaction in a period of time, the value of vwap results in a number that may crash the bot.
I tried with different tokens and the vwap number resulted in a zero value or in wrong number. 

I didn't test but as the vwap is a low value the bot could sell all tokens in the wallet by _mistake_ because the current price would be more than vwap (by mistake would be zero or a very low value).

Should be implemented a protection and the bot should **not** run this token **until** a transaction is made and the vwap value **updated**.

I hope this can be implemented in a next release.

Ex.
In image below the last transaction was 19hours ago. If the bot tries to calculate the vwap1h, vwap4h, vwap12h it will result in a wrong number. In the example below just vwap1day would result in a correct value.

![image](https://user-images.githubusercontent.com/51523705/105219302-13e37480-5b35-11eb-8563-33cb9735990d.png)

Image below shows vwap equal to zero in ping pong bot, but I tested with different tokens and I found another results different than zero or equal to one point something (1.xxx).

![image](https://user-images.githubusercontent.com/51523705/105219641-7472b180-5b35-11eb-9d14-457c6cddd542.png)

**Comment by CryptoGnome** [comment]
this is not a bug in the bot, only the UI. when there has been no trades the bot cant make VWAP so it uses last price.
