### ISSUE TITLE
limit swap bot - buy /eth worth of tokens

### ISSUE THREAD

**Issue by bugbib** [CryptoGnome/LimitSwap#115]
Currently we have to calculate the correct amount of tokens depending on our buy target, which is tricky considering slippage.

If you are trying to snipe a listing. Its  a shame because say you want buy up to .50 and the price hits .25 you could have bought twice the tokens.

If there was an option to buy say 1 eth of the said token up to .50(plus slippage) that would be the user experience easier. 

thanks

**Comment by CryptoGnome** [comment]
just set max tokens lower / half considering slippage as there will always be some

**Comment by bugbib** [comment]
I still think the feature makes the whole sniping experience a lot easier

________________________________
