### ISSUE TITLE
Pushover notifications

### ISSUE THREAD

**Issue by skerni** [CryptoGnome/LimitSwap#116]
It seems to be an error when the regional settings are set to comma for decimal symbol and dot for digit grouping symbol.
![image](https://user-images.githubusercontent.com/81652174/113054250-7bf3ae00-91a9-11eb-8a98-1ee279e7e65d.png)

resulting message is without a decimal:

💲 New Sell 💲: Sold 1876546254297244687357MARSH

**Comment by skerni** [comment]
After using the bot i saw the pattern. The bought notification is in x amount of TOKEN, should be x amount in ETH. Here the decimal seems to work and x is correct. The sold y amount is in TOKEN, the token is correct, but the y is not correct. It should use decimal. Above in example 18 decimal would result in 1876.546254297244687357MARSH

so, the regional setings is not an issue, i guess.

**Comment by CryptoGnome** [comment]
no longer supported
