### ISSUE TITLE
[Improvement idea] BSC - Clarifiy the "Current price" line 

### ISSUE THREAD

**Issue by tsarbuig** [CryptoGnome/LimitSwap#119]
I suggest to clarifiy the "Current price" line wording here, by adding the currency after the amount:
https://ibb.co/q5Jbj9M

- Current wording : "Current price POOCOIN = 1.41543" 

- Suggested improved wording : "Current price POOCOIN = 1.41543 **BUSD**"

**Comment by CryptoGnome** [comment]
Added
