### ISSUE TITLE
Enhanced logging

### ISSUE THREAD

**Issue by goneale** [CryptoGnome/LimitSwap#12]
It would be great to see after **_Transaction Sent Waiting 70 Seconds to Make sure it Confirms_** another message underneath "Transaction SELL OK." or trans.. BUY OK. as there was no confirmation.

Additionally, I would love to see a `limitswap.exe --logging:info` or something of the like to print all of the console output information to a `output.log` or something, which would reside side by side with the `error.log`
Eg, running output of this, with timestamp:
```
[2020-10-19 15:17:00] Transaction Sent Waiting 70 Seconds to Make sure it Confirms
[2020-10-19 15:17:00] Current Ticker yRise : $ 18.537269 | Buy Price 1 | Take Profit: 19.8 | Stop Loss: Not Enabled
[2020-10-19 15:17:00] Current Ticker yRise : $ 18.537269 | Buy Price 1 | Take Profit: 19.8 | Stop Loss: Not Enabled
```
Be very good for looking back on history, and helpful for submitting bug reports.

![image](https://user-images.githubusercontent.com/107109/96404345-0826a000-121e-11eb-92e7-62799d1576b2.png)

**Comment by CryptoGnome** [comment]
Added new logic to check the confirmation after sending so it will be much faster, and tell you that tx went through

**Comment by goneale** [comment]
@CryptoGnome  What do you think about the enhanced logging though? Would be great for historical backtracking.

**Comment by CryptoGnome** [comment]
Tell me what variable you would like to see I will do what I can

**Comment by goneale** [comment]
See how I have timestamped the log as an example above the console window? Just thought it would be great to output everything you are writing to the command window into a txt file, if it's turned on.
