### ISSUE TITLE
[Improvement idea] BSC - add comments in the token.json file

### ISSUE THREAD

**Issue by tsarbuig** [CryptoGnome/LimitSwap#120]
Hi,

Is it possible to add comments in the token.json file, so as it to be easier to understand?

Something like : 

     "SYMBOL": "WATCH",  // symbol of the token you want to buy
    "ADDRESS": "0x7A9f28EB62C791422Aa23CeAE1dA9C847cBeC9b0", // symbol of the token you want to buy
    "BASESYMBOL": "BUSD", // symbol of the token you want to trade with
    "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56", // address of the token you want to trade with
    "BUYAMOUNT": "1", // amount of token you want to buy each time
    "MAXAMOUNT": "0.5", // blablabla
    "BUYPRICE": "2", // blablabla
    "SELLAMOUNT": "25", // blablabla
    "SELLPRICE": "50", // blablabla
    "MOONBAG": "920", // blablabla
    "SLIPPAGE": "5", // blablabla
    "USECHAI": "false", // blablabla
    "GASBOOST": "25", // blablabla
    "GASLIMIT": "250000", // blablabla
    "MAXGAS": "50"

**Comment by CryptoGnome** [comment]
This is not possible with HSON however we are working on a WiKi
