### ISSUE TITLE
BSC - errror "sell() missing 1 required positional argument: 'token'"

### ISSUE THREAD

**Issue by tsarbuig** [CryptoGnome/LimitSwap#121]
When I use this tokens.json file, the program windows close, and I have this error:
`sell() missing 1 required positional argument: 'token'`

**tokens.json file content:**
[
  {
    "SYMBOL": "POOCOIN",
    "ADDRESS": "0xb27adaffb9fea1801459a1a81b17218288c097cc",
    "BASESYMBOL": "BUSD",
    "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
    "BUYAMOUNT": "1",
    "MAXAMOUNT": "0.5",
    "BUYPRICE": "0.50",
    "SELLAMOUNT": "25",
    "SELLPRICE": "0.80",
    "MOONBAG": "0",
    "SLIPPAGE": "3",
    "USECHAI": "false",
    "GASBOOST": "25",
    "GASLIMIT": "500",
    "MAXGAS": "500"
  }
]

**Comment by CryptoGnome** [comment]
Resolved
