### ISSUE TITLE
BSC [Enhancement]

### ISSUE THREAD

**Issue by GlimSpan** [CryptoGnome/LimitSwap#124]
Please could you make it possible to allow the user to set the amount to be sold as a percentage? For instance,  if the price hits X, the user may want to sell, Y% of whatever they are holding rather than a specific fixed number seeing as some of these deflationary tokens keep adding to how many tokens you have in total. It is not a stationary number that can be specified. This would also be useful in a scenario when you want to sell ALL tokens. You would be able to set it to 100% to sell all. It could lend itself to the Moonbag concept too (perhaps)

**Comment by CryptoGnome** [comment]
added in v3 as token amount
