### ISSUE TITLE
BSC. Error 'amountIn'  LimitSwap.BSC.v0.4

### ISSUE THREAD

**Issue by Smedik** [CryptoGnome/LimitSwap#126]
Windows 10 x64
I changed only settings file and try to run main.exe as administrator and get next error:

INFO: 2021-04-04 19:15:34,961 Current Tokens Staked = 25.0
INFO: 2021-04-04 19:15:34,961 Trader Price = 50 Tokens Staked
ERROR: 2021-04-04 19:15:36,965 quote_usd() missing 1 required positional argument: 'amountIn'
Traceback (most recent call last):
  File "main.py", line 312, in <module>
  File "main.py", line 303, in auth
  File "main.py", line 245, in run_trader
TypeError: quote_usd() missing 1 required positional argument: 'amountIn'

Tonen.js file the same 

[
  {
    "SYMBOL": "WATCH",
    "ADDRESS": "0x7A9f28EB62C791422Aa23CeAE1dA9C847cBeC9b0",
    "BASESYMBOL": "BUSD",
    "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
    "BUYAMOUNT": "1",
    "MAXAMOUNT": "0.5",
    "BUYPRICE": "2",
    "SELLAMOUNT": "25",
    "SELLPRICE": "50",
    "MOONBAG": "920",
    "SLIPPAGE": "5",
    "USECHAI": "false",
    "GASBOOST": "25",
    "GASLIMIT": "250000",
    "MAXGAS": "50"
  },
    {
    "SYMBOL": "SWIRL",
    "ADDRESS": "0x52d86850bc8207b520340B7E39cDaF22561b9E56",
    "BASESYMBOL": "BUSD",
    "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
    "BUYAMOUNT": "1",
    "MAXAMOUNT": "100",
    "BUYPRICE": "0.000000005",
    "SELLAMOUNT": "50",
    "SELLPRICE": "250",
    "MOONBAG": "50",
    "SLIPPAGE": "5",
    "USECHAI": "false",
    "GASBOOST": "25",
    "GASLIMIT": "250000",
    "MAXGAS": "50"

  }
]

**Comment by CryptoGnome** [comment]
resolved
