### ISSUE TITLE
Some tokens are not supported BSC

### ISSUE THREAD

**Issue by thereyrey** [CryptoGnome/LimitSwap#127]
INFO: 2021-04-05 13:36:17,682 Current Tokens Staked = 25.0
INFO: 2021-04-05 13:36:17,682 Trader Price = 50 Tokens Staked
INFO: 2021-04-05 13:36:20,124 SAFEMOON is not supported at the moment passing
INFO: 2021-04-05 13:36:22,380 SAFEMOON is not supported at the moment passing

![notsupported](https://user-images.githubusercontent.com/20780286/113570201-22a9d580-9614-11eb-9a19-833ebfd9c567.png)

**Comment by CryptoGnome** [comment]
Resolved
