### ISSUE TITLE
[BUG] Limitswap when retry ignores the price check or slippage

### ISSUE THREAD

**Issue by jondoeog** [CryptoGnome/LimitSwap#130]
after failed tx it doesn't respect slippage or sell price

example:
Oddz set to sell at 3.63$ price goes to 3.65$, bot tries to sell, failes (frontrun by other bots)
retries and sell go through at 3.43$
my slippage is at 1.5% 

same thing with other token yesterday
trying to sell at 48$, 1st failed tx, 2nd retry goes through and execution price 42$ while slippage set to 2%..

this is really annoying
in both cases it should fail again or not retry again

newest Limitswap bot (ETH chain)

**Comment by CryptoGnome** [comment]
fixed
