### ISSUE TITLE
BSC - Cannot sell token

### ISSUE THREAD

**Issue by thereyrey** [CryptoGnome/LimitSwap#133]
ERROR: 2021-04-06 18:00:49,122 {'statusCode': 500, 'message': 'cannot estimate', 'error': 'Internal Server Error'}
ERROR: 2021-04-06 18:00:52,025 {'statusCode': 500, 'message': 'cannot estimate', 'error': 'Internal Server Error'}
ERROR: 2021-04-06 18:00:55,574 {'statusCode': 500, 'message': 'cannot estimate', 'error': 'Internal Server Error'}

![image](https://user-images.githubusercontent.com/20780286/113741922-63801800-9702-11eb-87fa-dc85eec1b10e.png)

**Comment by thereyrey** [comment]
I have tried with bigger volume too on the same token (40M)

**Comment by CryptoGnome** [comment]
post you tokens json here

**Comment by thereyrey** [comment]
Im holding 44311405 tokens
To sell "ALL":
ERROR: 2021-04-06 19:12:30,779 {'statusCode': 500, 'message': 'cannot estimate', 'error': 'Internal Server Error'}
To sell "44311405":
Sell Signal Found for NCAT
NCAT Current Wallet Balance is : 44311405.8309783
Not enough tokens to trade

 {
  "SYMBOL": "NCAT",
  "ADDRESS": "0x0cf011a946f23a03ceff92a4632d5f9288c6c70d",
  "BASESYMBOL": "BUSD",
  "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
  "BUYAMOUNT": "10",
  "MAXAMOUNT": "200",
  "BUYPRICE": "0.000000000028",
  "SELLAMOUNT": "44311405",
  "SELLPRICE": "0.000000020",
  "MOONBAG": "0",
  "SLIPPAGE": "5",
  "LIQUIDITYCHECK": "TRUE",
  "LIQUIDTYWBNB": "10"
  }
