### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by thereyrey** [CryptoGnome/LimitSwap#134]
ERROR: 2021-04-06 19:38:56,820 '>' not supported between instances of 'float' and 'str'
Traceback (most recent call last):
  File "main.py", line 400, in <module>
  File "main.py", line 391, in auth
  File "main.py", line 326, in run_trader
  File "main.py", line 218, in buy
TypeError: '>' not supported between instances of 'float' and 'str'

**Comment by thereyrey** [comment]
{
  "SYMBOL": "PooCoin",
  "ADDRESS": "0xb27adaffb9fea1801459a1a81b17218288c097cc",
  "BASESYMBOL": "BUSD",
  "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
  "BUYAMOUNT": "10",
  "MAXAMOUNT": "1.5",
  "BUYPRICE": "0.6",
  "SELLAMOUNT": "5",
  "SELLPRICE": "1.1",
  "MOONBAG": "0",
  "SLIPPAGE": "5",
  "LIQUIDITYCHECK": "TRUE",
  "LIQUIDTYWBNB": "10"
  }

**Comment by CryptoGnome** [comment]
fixed
