### ISSUE TITLE
WBNB Current Wallet Balance is : 0.0

### ISSUE THREAD

**Issue by ebbrey** [CryptoGnome/LimitSwap#136]
Trying to make a 0.5 BNB purchase with 0.86 in the wallet.

First snipe buy fails with only a confirmation:
https://bscscan.com/tx/0x315652bb8ef9c322d071007c2d0b0c795a98f8a5dba25326c064d928486bee76

Then next:
Buy Signal Found
WBNB Current Wallet Balance is : 0.0
Current Liquidity Reserves: 238350533492.6177 WBNB
Not enough WBNBin wallet to make this trade...

**Comment by CryptoGnome** [comment]
you need WBNB bnb does not works on BSC swaps
