### ISSUE TITLE
Add a bot tilt function

### ISSUE THREAD

**Issue by joestu** [CryptoGnome/LimitSwap#140]
Hey mate...love ur and the teams work btw.

Can you add a bot tilt function if the first order is executed (as discussed on  TG), much apprecitated.

**Comment by CryptoGnome** [comment]
can you add more details here please

**Comment by joestu** [comment]
Yes, bot shall be killed after the first execution on BSC or ETH and can then be restarted with different .json settings. Could allow a whole new set of use cases for us.
