### ISSUE TITLE
BSC bot not working after selling signal

### ISSUE THREAD

**Issue by gukenji** [CryptoGnome/LimitSwap#142]
Hi,
Im trying to sell a coin in BSC but it keeps looping a sell order.
Log below:
INFO: 2021-04-09 23:27:50,838 Please Use Github & Telegram to ask about Buy Errors Below:
INFO: 2021-04-09 23:27:50,838 ***********************************************************
INFO: 2021-04-09 23:27:50,839 A Common Error if this says cannot estimate is slippage in the tokens.json, please try to increase first... 
ERROR: 2021-04-09 23:27:50,839 {'statusCode': 500, 'message': 'cannot estimate', 'error': 'Internal Server Error'}

I tried with BUSD, WBNB base token.
Tried 10, 15, 20, 25, 30% slippage
Tried 5, 10, 15 gas.

None of them worked.

Could you help me, please?

Thanks!

**Comment by gukenji** [comment]
Here's my tokens.json
[
 {
  "SYMBOL": "LIGHT",
  "ADDRESS": "0x7b9c3df47f3326fbc0674d51dc3eb0f2df29f37f",
  "BASESYMBOL": "BUSD",
  "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
  "BUYAMOUNT": "3000",
  "MAXAMOUNT": "2800",
  "BUYPRICE": "0.37",
  "SELLAMOUNT": "ALL",
  "SELLPRICE": "0.506",
  "MOONBAG": "0",
  "SLIPPAGE": "11",
  "GAS": "5",
  "LIQUIDITYCHECK": "false",
  "LIQUIDTYWBNB": "10"
  }
]

**Comment by GlimSpan** [comment]
The API used by the app is picking a price for the token but that price remains static even though there are significant amounts of trading happening on pancakeswap. The price shown should actually meet the sell criteria specified in Tokens.Json, however the sale is never executed. It just keeps repeating the sell order with the same price over and over but never completes. There is significant liquidity on the Token's Liquidity pool.

**Comment by GlimSpan** [comment]
![Screen Shot 2021-04-14 at 00 12 18](https://user-images.githubusercontent.com/81879010/114632712-2219da80-9cb7-11eb-86bc-6aab1932d55e.jpg)

**Comment by CryptoGnome** [comment]
this was confirmed to be a pancakeswap bug closing
