### ISSUE TITLE
BSC Bot stuck after send TX (no tx in BSCscan.com)

### ISSUE THREAD

**Issue by mrkss21** [CryptoGnome/LimitSwap#144]
Connected to Binance Smart Chain = True
Here is Latest Release Version on Github Please Make Sure You are Staying Updated =  v2.935
Connected to Ethereum BlockChain = True
Current Tokens Staked = 51.0
Pro Subscriptions Active
Checking Approvals Before Starting...
Checking Approval Status for  ZDCASH
Current Price ZDCASH = 0.0019001596332566 WBNB
Buy Signal Found for ZDCASH
ZDCASH Current Wallet Balance is : 0.0
WBNB Current Wallet Balance is : 0.99
Current Liquidity Reserves: 78.73295454545458 WBNB
Sending Buy Order for ZDCASH...
Print TX =  0x0e4cd11a0aac0ac497ccee6a141231a95cfc2a157b79a3c2a878a74325d73637
Waiting for TX to Confirm....
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............
.........waiting............

as we see - bot waiting for confirm, but some reason TX not put in BSC.

my config is 

[
 {
  "SYMBOL": "ZDCASH",
  "ADDRESS": "0xdd15a40116316d7c8983c8d3fcf52f518d52575e",
  "BASESYMBOL": "WBNB",
  "BASEADDRESS": "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c",
  "BUYAMOUNT": "0.05",
  "MAXAMOUNT": "50",
  "BUYPRICE": "0.002",
  "SELLAMOUNT": "ALL",
  "SELLPRICE": "0.01",
  "MOONBAG": "0",
  "SLIPPAGE": "49",
  "GAS": "20",
  "LIQUIDITYCHECK": "TRUE",
  "LIQUIDTYWBNB": "0.01"
 }
]

**Comment by CryptoGnome** [comment]
Adding, timeout to loop
