### ISSUE TITLE
BSC bot showing "statusCode': 500, 'message': 'you may not have enough ETH balance for gas fee'

### ISSUE THREAD

**Issue by tsarbuig** [CryptoGnome/LimitSwap#145]
hi, a user has faced this error when bot tries to buy:

```
INFO: 2021-04-12 03:56:34,804 A Common Error if this says cannot estimate is slippage in the tokens.json, please try to increase first... 
ERROR: 2021-04-12 03:56:34,804 {'statusCode': 500, 'message': 'you may not have enough ETH balance for gas fee', 'error': 'Internal Server Error'}
```

I checked with him, and he had plenty of money on his wallet (0x1a622440c2f34de39d7451C76aE6420f9fA5FFb1) : 
- ETH
- BNB
- WBNB

his tokens.json is  :  

```
[
 {
  "SYMBOL": "SPOWL",
  "ADDRESS": "0xfb8e88409029697e59a11c14783ccbf224eded42",
  "BASESYMBOL": "WBNB",
  "BASEADDRESS": "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c",
  "BUYAMOUNT": "0.1",
  "MAXAMOUNT": "50000000000",
  "BUYPRICE": "0.000000000008",
  "SELLAMOUNT": "ALL",
  "SELLPRICE": "0.0000000000093",
  "MOONBAG": "0",
  "SLIPPAGE": "8",
  "GAS": "5",
  "LIQUIDITYCHECK": "TRUE",
  "LIQUIDTYWBNB": "10"
  }
]
```

it's very strange because it works for me for the same token...

**Comment by touftaf** [comment]
Hello it's me who is facing this issue. Also i can add some precisions, i made some tests and here are my results : 

The bot tries to sell 60131602349.08213 tokens.

in  1inch, when i try to sell this exact amount of token, it tells me "insufficient balance".

when i remove the last digit after the coma (60131602349.0821), it works for swapping.

I think that 1inch doesn't deal with too many digits after the coma.

Hope this will be fixed

**Comment by CryptoGnome** [comment]
> Hello it's me who is facing this issue. Also i can add some precisions, i made some tests and here are my results :
> 
> The bot tries to sell 60131602349.08213 tokens.
> 
> in 1inch, when i try to sell this exact amount of token, it tells me "insufficient balance".
> 
> when i remove the last digit after the coma (60131602349.0821), it works for swapping.
> 
> I think that 1inch doesn't deal with too many digits after the coma.
> 
> Hope this will be fixed

thank you will look today

**Comment by touftaf** [comment]
So ?
