### ISSUE TITLE
ETH Bot asking for LIMIT uniswap LP tokens

### ISSUE THREAD

**Issue by cryptopunk23** [CryptoGnome/LimitSwap#147]
I had 51 Limit Tokens in my wallet. When I tried to run ETH bot to snipe a listing, it asks for LIMIT uniswap LP Tokens. 

It correctly detected my wallet and the amount of ETH at the top of the GUI.

I tried with a few different symbols and it is giving me the same error. 

Attached is the error. 
<img width="992" alt="Screen Shot 2021-04-14 at 23 00 39" src="https://user-images.githubusercontent.com/82530490/114744698-2bb74700-9d78-11eb-84b0-25aed96d9222.png">

**Comment by CryptoGnome** [comment]
turn of liquidity provider in settings
