### ISSUE TITLE
BSC bot sold with price much less than SELLPRICE

### ISSUE THREAD

**Issue by cyberZvezd** [CryptoGnome/LimitSwap#148]
Hi there,
My first try was not good.
I set to bot to sell 20KPADs with the price 3.30BUSD
But when I checked the results I found that it sold for around 2.48USD
https://bscscan.com/tx/0xc7ab831bb138b7910759a984802226313312de638a06679417c6d311002b9144

here comes screenshots..

![tokenJSON](https://user-images.githubusercontent.com/82567547/114825715-c5223f80-9df0-11eb-9abb-761f2638b78e.jpg)
![output](https://user-images.githubusercontent.com/82567547/114825727-c7849980-9df0-11eb-81d7-e0a85fea440f.jpg)

If I understand right that slippage parameter should control these kind of situations. Is not it?
The result is around minus 10$ :(
Lucky that first try was with small amount :))

**Comment by cyberZvezd** [comment]
One more time same thing happen :((
I closed the terminal to cancel the transaction, but the bot is super fast ))

https://bscscan.com/tx/0x8a6e1dbf43d29fc16a1f99cce6461eda885fde84a2b3b2f616826f8d124f1c58

This is transaction hash. My SELLPRICE was set to 4.5. And I saw the Current Price ~ 9BUSD.

**Comment by CryptoGnome** [comment]
In  Progress
