### ISSUE TITLE
Make it possible to use wETH as the buy pair on ETH bot

### ISSUE THREAD

**Issue by alefantozzi** [CryptoGnome/LimitSwap#152]
Most of the transaction in ERC20 with ETH has first to be wrapped (wETH) before  buy a token. When you already have wETH in the wallet and uses it instead to ake a buy, the transaction happens faster and cheaper. Please find a way to have the option to chenga the buy pair to wETH

**Comment by CryptoGnome** [comment]
fixed in v3
