### ISSUE TITLE
Add option to set Gaslimit manually | BSC BOT

### ISSUE THREAD

**Issue by manz30** [CryptoGnome/LimitSwap#154]
many errors that i got is all about "can't estimate the gas price", could you please add option to set the gaslimit manually ? so below the GASPRICE there is GASLIMIT option that we can set it by ourself, i think thats will resolve most of the problem

**Comment by CryptoGnome** [comment]
what error?

**Comment by manz30** [comment]
Fixed at LimitSwap v2.9363, good job sir
