### ISSUE TITLE
A Common Error has occurred please check your errors.log for more info

### ISSUE THREAD

**Issue by LudoAAV** [CryptoGnome/LimitSwap#157]
Hi, today I tried the bot for the first time on Pancakeswap, buying Cake with BUSD.
The different buying orders went through but I still received the following error message in the command window:

"A Common Error has occurred please check your errors.log for more info
Current Price CAKE = 20.955025970695573504 BUSD
Buy Signal Found for CAKE
CAKE Current Wallet Balance is : 0.2607950824467166
BUSD Current Wallet Balance is : 12.738891738379946
Current Liquidity Reserves: 982289.8776645579 WBNB
Sending Buy Order for CAKE...
Print TX =  0xadab6cc0cea1551bd518621743db77644f79a0d88064c5fcd2b6e6b4dc4b5348
Waiting for TX to Confirm...."

The Tokens.json is set up as followed:
 "SYMBOL": "CAKE",
  "ADDRESS": "0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82",
  "BASESYMBOL": "BUSD",
  "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
  "BUYAMOUNT": "0.5",
  "MAXAMOUNT": "1",
  "BUYPRICE": "25.5",
  "SELLAMOUNT": "ALL",
  "SELLPRICE": "100",
  "MOONBAG": "0",
  "SLIPPAGE": "49",
  "GAS": "20",
  "LIQUIDITYCHECK": "TRUE",
  "LIQUIDTYWBNB": "10"

The error log says:
***********************************************************************
INFO: 2021-04-18 13:11:36,429 For Help & To Learn More About how the bot works please visit our wiki here:
INFO: 2021-04-18 13:11:36,429 https://limitswap.gitbook.io/limitswap/
INFO: 2021-04-18 13:11:36,429 *************************************************************************************
INFO: 2021-04-18 13:11:36,984 Here is Latest Release Version  on Github Please Make Sure You are Staying Updated = v2.9362
INFO: 2021-04-18 13:11:38,797 Current Tokens Staked = 50.0
INFO: 2021-04-18 13:11:38,798 Trader Price = 50 Tokens Staked
INFO: 2021-04-18 13:11:49,112 ***********************************************************
INFO: 2021-04-18 13:11:49,112 Please Use Github & Telegram to ask about Buy Errors Below:
INFO: 2021-04-18 13:11:49,112 ***********************************************************
INFO: 2021-04-18 13:11:49,112 A Common Error if this says cannot estimate is slippage in the tokens.json, please try to increase first... 
ERROR: 2021-04-18 13:11:49,113 {'fromToken': {'symbol': 'BUSD', 'name': 'BUSD Token', 'decimals': 18, 'address': '0xe9e7cea3dedca5984780bafc599bd69add087d56', 'logoURI': 'https://tokens.1inch.exchange/0x4fabb145d64652a948d72533023f6e7a623c7c53.png'}, 'toToken': {'symbol': 'CAKE', 'name': 'PancakeSwap Token', 'decimals': 18, 'address': '0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82', 'logoURI': 'https://tokens.1inch.exchange/0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82.png'}, 'toTokenAmount': '23639213066221039', 'fromTokenAmount': '500000000000000000', 'protocols': [[[{'name': 'PANCAKESWAP', 'part': 100, 'fromTokenAddress': '0xe9e7cea3dedca5984780bafc599bd69add087d56', 'toTokenAddress': '0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82'}]]], 'tx': {'from': '0xb335a3eC7f789457778C60B42B93c9591e2FDbdF', 'to': '0x11111112542d85b3ef69ae05771c2dccff4faa26', 'data': '0x7c025200000000000000000000000000c603a00595d5f8ea8d93c5c338c00ff29dba625800000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000180000000000000000000000000e9e7cea3dedca5984780bafc599bd69add087d560000000000000000000000000e09fabb73bd3ade0a17ecc321fd13a19e81ce820000000000000000000000000ed8e0a2d99643e1e65cca22ed4424090b8b7458000000000000000000000000b335a3ec7f789457778c60b42b93c9591e2fdbdf00000000000000000000000000000000000000000000000006f05b59d3b20000000000000000000000000000000000000000000000000000002ad4ddedc44a39000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000001a0800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000a4c9f12e9d0000000000000000000000000ed8e0a2d99643e1e65cca22ed4424090b8b7458000000000000000000000000e9e7cea3dedca5984780bafc599bd69add087d560000000000000000000000000e09fabb73bd3ade0a17ecc321fd13a19e81ce82000000000000000000000002c603a00595d5f8ea8d93c5c338c00ff29dba6258000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000001a4b3af37c0000000000000000000000000000000000000000000000000000000000000008080000000000000000000000000000000000000000000000000000000000000440000000000000000000000000e09fabb73bd3ade0a17ecc321fd13a19e81ce82000000000000000000000000000000010000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000064d1660f990000000000000000000000000e09fabb73bd3ade0a17ecc321fd13a19e81ce82000000000000000000000000b335a3ec7f789457778c60b42b93c9591e2fdbdf00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', 'value': '0', 'gasPrice': '15000000000', 'gas': 202764}}
INFO: 2021-04-18 13:12:00,772 **************

I am using the last BSC bot version.

Is this error something I should worry about?

**Comment by CryptoGnome** [comment]
no disregaurd
