### ISSUE TITLE
 Wei Value Error on BSC 2.9362

### ISSUE THREAD

**Issue by GlimSpan** [CryptoGnome/LimitSwap#158]
Trying to snipe with version 2.9362 BSC I got this error:

ERROR: 2021-04-18 18:04:10,450 Resulting wei value must be between 1 and 2**256 - 1
Traceback (most recent call last):
  File "main.py", line 531, in <module>
  File "main.py", line 521, in auth
  File "main.py", line 436, in run_trader
  File "main.py", line 320, in sell
  File "eth_utils\currency.py", line 100, in to_wei
ValueError: Resulting wei value must be between 1 and 2**256 - 1

Here are the Jsons. Tried with and without decimals.  Failed both ways. Animated Gif attached showing the entire process.
[
{
  "SYMBOL": "SAFECHAOS",
  "ADDRESS": "0x1814cf3f0e7952BEF96e59168855029356375993",
  "BASESYMBOL": "BUSD",
  "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
  "BUYAMOUNT": "200.00",
  "MAXAMOUNT": "199.00",
  "BUYPRICE": "0.008",
  "SELLAMOUNT": "ALL",
  "SELLPRICE": "0.02",
  "MOONBAG": "5000",
  "SLIPPAGE": "25",
  "GAS": "5",
  "LIQUIDITYCHECK": "TRUE",
  "LIQUIDTYWBNB": "5"
  }
]
[
 
{
  "SYMBOL": "SAFECHAOS",
  "ADDRESS": "0x1814cf3f0e7952BEF96e59168855029356375993",
  "BASESYMBOL": "BUSD",
  "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
  "BUYAMOUNT": "200",
  "MAXAMOUNT": "199",
  "BUYPRICE": "0.008",
  "SELLAMOUNT": "ALL",
  "SELLPRICE": "0.02",
  "MOONBAG": "5000",
  "SLIPPAGE": "25",
  "GAS": "5",
  "LIQUIDITYCHECK": "TRUE",
  "LIQUIDTYWBNB": "5"
  }
]

**Comment by seekerp** [comment]
Yes, i've had this error as well, and after tweaking the setting of tokens.json, i've found out that when the sell price has hit the preset sell price, and the wallet does not have any amount to sell, it will have this wei value error and auto close the program.

**Comment by CryptoGnome** [comment]
fixed
