### ISSUE TITLE
Impossible to buy on DXsale

### ISSUE THREAD

**Issue by tsarbuig** [CryptoGnome/LimitSwap#159]
hi, many customers ask me if we can buy on DXsale

Today I tried to do it, and I had this error : 
<img width="892" alt="Capture d’écran 2021-04-19 à 00 02 35" src="https://user-images.githubusercontent.com/70858574/115162239-b2cf2c80-a0a2-11eb-8e84-a4eb34807bc5.png">

Json file : 
```
[
 {
  "SYMBOL": "Presale CatDoge",
  "ADDRESS": "0xfda118581fFB22F4B50218deF81646ecC41d2FA3",
  "BASESYMBOL": "WBNB",
  "BASEADDRESS": "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c",
  "BUYAMOUNT": "0.1",
  "MAXAMOUNT": "0.00000001",
  "BUYPRICE": "1",
  "SELLAMOUNT": "ALL",
  "SELLPRICE": "2",
  "MOONBAG": "0",
  "SLIPPAGE": "13",
  "GAS": "5",
  "LIQUIDITYCHECK": "TRUE",
  "LIQUIDTYWBNB": "10"
  }
]
```

Dxsale link : https://dxsale.app/app/pages/defipresale?saleID=1323&chain=BSC
Presale Address: 0xfda118581fFB22F4B50218deF81646ecC41d2FA3
Token Address: 0xc1fD6B60Dc003Fcf2cc1f2aed060Bf3f503C6e98

<img width="555" alt="Capture d’écran 2021-04-19 à 00 04 27" src="https://user-images.githubusercontent.com/70858574/115162255-d4301880-a0a2-11eb-92e1-38e41be9ef4b.png">

Do you think we could do something?

**Comment by CryptoGnome** [comment]
took a look not possible
