### ISSUE TITLE
Error logs, bot keeps shutting down. It has never stayed on longer than 3 hours.

### ISSUE THREAD

**Issue by JevScud** [CryptoGnome/LimitSwap#160]
I can't get any answers on the Telegram about any issues I'm having so posting here. Bot keeps shutting down. I've been trying to test it before I put it on a VPS but not had much luck in getting it to run constantly. Thanks for your help

######    Error 1 ########
INFO: 2021-04-17 16:41:14,817 A Common Error if this says cannot estimate is slippage in the tokens.json, please try to increase first... 
ERROR: 2021-04-17 16:41:14,818 {'fromToken': {'symbol': 'BUSD', 'name': 'BUSD Token', 'decimals': 18, 'address': '0xe9e7cea3dedca5984780bafc599bd69add087d56', 'logoURI': 'https://tokens.1inch.exchange/0x4fabb145d64652a948d72533023f6e7a623c7c53.png'}, 'toToken': {'symbol': 'BSCPAD', 'name': 'BSCPAD.com', 'decimals': 18, 'address': '0x5a3010d4d8d3b5fb49f8b6e57fb9e48063f16700', 'logoURI': 'https://tokens.1inch.exchange/0x5a3010d4d8d3b5fb49f8b6e57fb9e48063f16700.png'}, 'toTokenAmount': '123050251234243704684', 'fromTokenAmount': '500000000000000000000', 'protocols': [[[{'name': 'PANCAKESWAP', 'part': 100, 'fromTokenAddress': '0xe9e7cea3dedca5984780bafc599bd69add087d56', 'toTokenAddress': '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c'}], [{'name': 'PANCAKESWAP', 'part': 100, 'fromTokenAddress': '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c', 'toTokenAddress': '0x5a3010d4d8d3b5fb49f8b6e57fb9e48063f16700'}]]], 'tx': {'from': '0xf3bE623D78Be6ad086a981D0cb6cFD3D4BA4750a', 'to': '0x11111112542d85b3ef69ae05771c2dccff4faa26', 'data': '0x7c025200000000000000000000000000c603a00595d5f8ea8d93c5c338c00ff29dba625800000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000180000000000000000000000000e9e7cea3dedca5984780bafc599bd69add087d560000000000000000000000005a3010d4d8d3b5fb49f8b6e57fb9e48063f167000000000000000000000000001b96b92314c44b159149f7e0303511fb2fc4774f000000000000000000000000f3be623d78be6ad086a981d0cb6cfd3d4ba4750a00000000000000000000000000000000000000000000001b1ae4d6e2ef500000000000000000000000000000000000000000000000000006564831f8ceaf37d900000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005c000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000000000000000000000000000000000000320800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000a4c9f12e9d0000000000000000000000001b96b92314c44b159149f7e0303511fb2fc4774f000000000000000000000000e9e7cea3dedca5984780bafc599bd69add087d56000000000000000000000000bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c0000000000000000000000021e47da535d9e96e2f9348d00c18fbe967566bc28000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000a4c9f12e9d0000000000000000000000001e47da535d9e96e2f9348d00c18fbe967566bc28000000000000000000000000bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c0000000000000000000000005a3010d4d8d3b5fb49f8b6e57fb9e48063f16700000000000000000000000002c603a00595d5f8ea8d93c5c338c00ff29dba6258000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000001a4b3af37c0000000000000000000000000000000000000000000000000000000000000008080000000000000000000000000000000000000000000000000000000000000440000000000000000000000005a3010d4d8d3b5fb49f8b6e57fb9e48063f16700000000000000000000000000000000010000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000064d1660f990000000000000000000000005a3010d4d8d3b5fb49f8b6e57fb9e48063f16700000000000000000000000000f3be623d78be6ad086a981d0cb6cfd3d4ba4750a00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', 'value': '0', 'gasPrice': '5000000000', 'gas': 319573}}
INFO: 2021-04-17 16:45:18,199 ***********************************************************
INFO: 2021-04-17 16:45:18,200 Please Use Github & Telegram to ask about Buy Errors Below:
INFO: 2021-04-17 16:45:18,200 ***********************************************************
INFO: 2021-04-17 16:45:18,200 A Common Error if this says cannot estimate is slippage in the tokens.json, please try to increase first... 
ERROR: 2021-04-17 16:45:18,200 {'fromToken': {'symbol': 'BUSD', 'name': 'BUSD Token', 'decimals': 18, 'address': '0xe9e7cea3dedca5984780bafc599bd69add087d56', 'logoURI': 'https://tokens.1inch.exchange/0x4fabb145d64652a948d72533023f6e7a623c7c53.png'}, 'toToken': {'symbol': 'BSCPAD', 'name': 'BSCPAD.com', 'decimals': 18, 'address': '0x5a3010d4d8d3b5fb49f8b6e57fb9e48063f16700', 'logoURI': 'https://tokens.1inch.exchange/0x5a3010d4d8d3b5fb49f8b6e57fb9e48063f16700.png'}, 'toTokenAmount': '122733381739940610624', 'fromTokenAmount': '500000000000000000000', 'protocols': [[[{'name': 'PANCAKESWAP', 'part': 100, 'fromTokenAddress': '0xe9e7cea3dedca5984780bafc599bd69add087d56', 'toTokenAddress': '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c'}], [{'name': 'PANCAKESWAP', 'part': 100, 'fromTokenAddress': '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c', 'toTokenAddress': '0x5a3010d4d8d3b5fb49f8b6e57fb9e48063f16700'}]]], 'tx': {'from': '0xf3bE623D78Be6ad086a981D0cb6cFD3D4BA4750a', 'to': '0x11111112542d85b3ef69ae05771c2dccff4faa26', 'data': '0x7c025200000000000000000000000000c603a00595d5f8ea8d93c5c338c00ff29dba625800000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000180000000000000000000000000e9e7cea3dedca5984780bafc599bd69add087d560000000000000000000000005a3010d4d8d3b5fb49f8b6e57fb9e48063f167000000000000000000000000001b96b92314c44b159149f7e0303511fb2fc4774f000000000000000000000000f3be623d78be6ad086a981d0cb6cfd3d4ba4750a00000000000000000000000000000000000000000000001b1ae4d6e2ef500000000000000000000000000000000000000000000000000006521abc66e8fedbbc00000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005c000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000000000000000000000000000000000000320800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000a4c9f12e9d0000000000000000000000001b96b92314c44b159149f7e0303511fb2fc4774f000000000000000000000000e9e7cea3dedca5984780bafc599bd69add087d56000000000000000000000000bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c0000000000000000000000021e47da535d9e96e2f9348d00c18fbe967566bc28000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000a4c9f12e9d0000000000000000000000001e47da535d9e96e2f9348d00c18fbe967566bc28000000000000000000000000bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c0000000000000000000000005a3010d4d8d3b5fb49f8b6e57fb9e48063f16700000000000000000000000002c603a00595d5f8ea8d93c5c338c00ff29dba6258000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000001a4b3af37c0000000000000000000000000000000000000000000000000000000000000008080000000000000000000000000000000000000000000000000000000000000440000000000000000000000005a3010d4d8d3b5fb49f8b6e57fb9e48063f16700000000000000000000000000000000010000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000064d1660f990000000000000000000000005a3010d4d8d3b5fb49f8b6e57fb9e48063f16700000000000000000000000000f3be623d78be6ad086a981d0cb6cfd3d4ba4750a00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', 'value': '0', 'gasPrice': '5000000000', 'gas': 305318}}
INFO: 2021-04-17 16:45:29,949 ***********************************************************
INFO: 2021-04-17 16:45:29,949 Please Use Github & Telegram to ask about Buy Errors Below:
INFO: 2021-04-17 16:45:29,949 ***********************************************************
INFO: 2021-04-17 16:45:29,949 A Common Error if this says cannot estimate is slippage in the tokens.json, please try to increase first... 
ERROR: 2021-04-17 16:45:29,950 {'fromToken': {'symbol': 'BUSD', 'name': 'BUSD Token', 'decimals': 18, 'address': '0xe9e7cea3dedca5984780bafc599bd69add087d56', 'logoURI': 'https://tokens.1inch.exchange/0x4fabb145d64652a948d72533023f6e7a623c7c53.png'}, 'toToken': {'symbol': 'BSCPAD', 'name': 'BSCPAD.com', 'decimals': 18, 'address': '0x5a3010d4d8d3b5fb49f8b6e57fb9e48063f16700', 'logoURI': 'https://tokens.1inch.exchange/0x5a3010d4d8d3b5fb49f8b6e57fb9e48063f16700.png'}, 'toTokenAmount': '122729489804534737958', 'fromTokenAmount': '500000000000000000000', 'protocols': [[[{'name': 'PANCAKESWAP', 'part': 100, 'fromTokenAddress': '0xe9e7cea3dedca5984780bafc599bd69add087d56', 'toTokenAddress': '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c'}], [{'name': 'PANCAKESWAP', 'part': 100, 'fromTokenAddress': '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c', 'toTokenAddress': '0x5a3010d4d8d3b5fb49f8b6e57fb9e48063f16700'}]]], 'tx': {'from': '0xf3bE623D78Be6ad086a981D0cb6cFD3D4BA4750a', 'to': '0x11111112542d85b3ef69ae05771c2dccff4faa26', 'data': '0x7c025200000000000000000000000000c603a00595d5f8ea8d93c5c338c00ff29dba625800000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000180000000000000000000000000e9e7cea3dedca5984780bafc599bd69add087d560000000000000000000000005a3010d4d8d3b5fb49f8b6e57fb9e48063f167000000000000000000000000001b96b92314c44b159149f7e0303511fb2fc4774f000000000000000000000000f3be623d78be6ad086a981d0cb6cfd3d4ba4750a00000000000000000000000000000000000000000000001b1ae4d6e2ef500000000000000000000000000000000000000000000000000006520d99b12d01ed2400000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005c000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000001c00000000000000000000000000000000000000000000000000000000000000320800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000a4c9f12e9d0000000000000000000000001b96b92314c44b159149f7e0303511fb2fc4774f000000000000000000000000e9e7cea3dedca5984780bafc599bd69add087d56000000000000000000000000bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c0000000000000000000000021e47da535d9e96e2f9348d00c18fbe967566bc28000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000a4c9f12e9d0000000000000000000000001e47da535d9e96e2f9348d00c18fbe967566bc28000000000000000000000000bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c0000000000000000000000005a3010d4d8d3b5fb49f8b6e57fb9e48063f16700000000000000000000000002c603a00595d5f8ea8d93c5c338c00ff29dba6258000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000001a4b3af37c0000000000000000000000000000000000000000000000000000000000000008080000000000000000000000000000000000000000000000000000000000000440000000000000000000000005a3010d4d8d3b5fb49f8b6e57fb9e48063f16700000000000000000000000000000000010000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000064d1660f990000000000000000000000005a3010d4d8d3b5fb49f8b6e57fb9e48063f16700000000000000000000000000f3be623d78be6ad086a981d0cb6cfd3d4ba4750a00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', 'value': '0', 'gasPrice': '5000000000', 'gas': 305318}}
ERROR: 2021-04-18 04:49:06,724 Extra data: line 1 column 5 (char 4)
Traceback (most recent call last):
  File "main.py", line 378, in quote_usd
  File "requests\models.py", line 897, in json
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
ERROR: 2021-04-18 04:49:06,959 Extra data: line 1 column 5 (char 4)
Traceback (most recent call last):
  File "main.py", line 378, in quote_usd
  File "requests\models.py", line 897, in json
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 531, in <module>
  File "main.py", line 518, in auth
  File "main.py", line 466, in run_pro
  File "main.py", line 392, in quote_usd
  File "requests\models.py", line 897, in json
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 340, in decode
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

#########  Error 2  ########

ERROR: 2021-04-18 15:06:14,324 Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "main.py", line 378, in quote_usd
  File "requests\models.py", line 897, in json
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
ERROR: 2021-04-18 16:48:28,422 {'code': -32603, 'message': 'handle request error'}
Traceback (most recent call last):
  File "main.py", line 154, in check_decimals2
  File "web3\contract.py", line 954, in call
  File "web3\contract.py", line 1499, in call_contract_function
  File "eth_utils\functional.py", line 45, in inner
  File "web3\eth.py", line 432, in call
  File "web3\manager.py", line 153, in request_blocking
ValueError: {'code': -32603, 'message': 'handle request error'}
ERROR: 2021-04-18 16:48:28,425 local variable 'DECIMALS' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 531, in <module>
  File "main.py", line 518, in auth
  File "main.py", line 466, in run_pro
  File "main.py", line 372, in quote_usd
  File "main.py", line 160, in check_decimals2
UnboundLocalError: local variable 'DECIMALS' referenced before assignment

##################   ERROR 3   ###################

ERROR: 2021-04-20 13:35:23,671 {'code': -32603, 'message': 'handle request error'}
Traceback (most recent call last):
  File "main.py", line 154, in check_decimals2
  File "web3\contract.py", line 954, in call
  File "web3\contract.py", line 1499, in call_contract_function
  File "eth_utils\functional.py", line 45, in inner
  File "web3\eth.py", line 432, in call
  File "web3\manager.py", line 153, in request_blocking
ValueError: {'code': -32603, 'message': 'handle request error'}
ERROR: 2021-04-20 13:35:23,884 local variable 'DECIMALS' referenced before assignment
Traceback (most recent call last):
  File "main.py", line 531, in <module>
  File "main.py", line 518, in auth
  File "main.py", line 466, in run_pro
  File "main.py", line 372, in quote_usd
  File "main.py", line 160, in check_decimals2
UnboundLocalError: local variable 'DECIMALS' referenced before assignment

**Comment by CryptoGnome** [comment]
are you on the latest version?
As it shoudl handle these errors fine

**Comment by CryptoGnome** [comment]
deprecated
