### ISSUE TITLE
Make LimitSwap work on launchs of BSCPad (for whitelisted users)

### ISSUE THREAD

**Issue by alefantozzi** [CryptoGnome/LimitSwap#161]
I'm a BSCPad Launchpad holder and have been whitelisted for the recent launchs. They have a system were some people who meet certain criteria get whitelisted and are able to buy a limited amount of tokens before the public. 

I've tested LimitSwap last time and it didn't work during the whitelist period. I was able to buy myself in PancakeSwap. During the whitelist period the "error" shown on the log was:

"
INFO: 2021-04-17 **11:00:02,275** KEL is not supported at the moment passing
INFO: 2021-04-17 11:00:04,659 ***********************************************************
INFO: 2021-04-17 11:00:04,660 Please Use Github & Telegram to ask about Buy Errors Below:
INFO: 2021-04-17 11:00:04,660 ***********************************************************
INFO: 2021-04-17 11:00:04,660 A Common Error if this says cannot estimate is slippage in the tokens.json, please try to increase first... 
ERROR: 2021-04-17 11:00:04,660 {'statusCode': 500, 'message': 'cannot estimate', 'error': 'Internal Server Error'}
INFO: 2021-04-17 11:00:05,472 ***********************************************************
INFO: 2021-04-17 11:00:05,473 Please Use Github & Telegram to ask about Buy Errors Below:
INFO: 2021-04-17 11:00:05,473 ***********************************************************
INFO: 2021-04-17 11:00:05,473 A Common Error if this says cannot estimate is slippage in the tokens.json, please try to increase first... 
ERROR: 2021-04-17 11:00:05,474 {'statusCode': 500, 'message': 'cannot estimate', 'error': 'Internal Server Error'}
......."

As you can see, as soon as liquidity was added (11:00:02), LimitSwap saw it and started trying to buy. It kept giving the error of slippage (which is the same error people who are not whitelisted receive from PancakeSwap when trying to buy). 

As soon whitelist was over it had this last message on error log. The bot successfully placed a buy right after that:

"
ERROR: 2021-04-17 11:04:02,798 {'fromToken': {'symbol': 'WBNB', 'name': 'Wrapped BNB', 'decimals': 18, 'address': '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c', 'logoURI': 'https://tokens.1inch.exchange/0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c.png'}, 'toToken': {'address': '0x4e1b16ef22935a575a6811d4616f98c4077e4408', 'decimals': 18, 'symbol': 'KEL', 'name': 'KelVPN token', 'logoURI': 'https://etherscan.io/images/main/empty-token.png', 'isCustom': True}, 'toTokenAmount': '81862726017488339792', 'fromTokenAmount': '518100000000000000', 'protocols': [[[{'name': 'PANCAKESWAP', 'part': 100, 'fromTokenAddress': '0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c', 'toTokenAddress': '0x4e1b16ef22935a575a6811d4616f98c4077e4408'}]]], 'tx': {'from': '0x2Ef846F777d393ccc9ED1aaC224095Af6d3aa16c', 'to': '0x11111112542d85b3ef69ae05771c2dccff4faa26', 'data': '0x7c025200000000000000000000000000c603a00595d5f8ea8d93c5c338c00ff29dba625800000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000180000000000000000000000000bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c0000000000000000000000004e1b16ef22935a575a6811d4616f98c4077e4408000000000000000000000000f38963b0cbe97963009b34b9250cebd1b40424f60000000000000000000000002ef846f777d393ccc9ed1aac224095af6d3aa16c0000000000000000000000000000000000000000000000000730a9347a2140000000000000000000000000000000000000000000000000024365c2f2daef7bed000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000044000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000001a0800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000a4c9f12e9d000000000000000000000000f38963b0cbe97963009b34b9250cebd1b40424f6000000000000000000000000bb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c0000000000000000000000004e1b16ef22935a575a6811d4616f98c4077e4408000000000000000000000002c603a00595d5f8ea8d93c5c338c00ff29dba6258000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000001a4b3af37c0000000000000000000000000000000000000000000000000000000000000008080000000000000000000000000000000000000000000000000000000000000440000000000000000000000004e1b16ef22935a575a6811d4616f98c4077e4408000000000000000000000000000000010000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000064d1660f990000000000000000000000004e1b16ef22935a575a6811d4616f98c4077e44080000000000000000000000002ef846f777d393ccc9ed1aac224095af6d3aa16c00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', 'value': '0', 'gasPrice': '5000000000', 'gas': 232609}}"

I understand LimitSwap routes though 1Inch and maybe this is the reason why it doesn't work. Is it possible to have the bot buying straight from PancakeSwap?

If this is not the reason I can run some tests to find out the problem. What do you recommend? Tomorrow they will have another launch and I'm whitelisted again.

**Comment by 0AD0** [comment]
Can’t wait to see the answer to this +1

**Comment by CryptoGnome** [comment]
revisit in v3
