### ISSUE TITLE
Bot price discovery

### ISSUE THREAD

**Issue by Asian-Cutie** [CryptoGnome/LimitSwap#164]
I'm trying to buy safemoon at 0.01 current market but its not working, as a test.
Also the issue was that safemoon's price on pancakeswap was different than the bot
Price of safemoon is around 0.00000408 currently

https://media.discordapp.net/attachments/763150064826712094/834843149003522048/Screen_Shot_2021-04-22_at_7.24.00_AM.png?width=945&height=591

safemoon/bnb

https://media.discordapp.net/attachments/763150064826712094/834844314722238515/Screen_Shot_2021-04-22_at_7.32.45_AM.png?width=903&height=592

INFO: 2021-04-22 17:30:50,107 *************************************************************************************
INFO: 2021-04-22 17:30:50,107 For Help & To Learn More About how the bot works please visit our wiki here:
INFO: 2021-04-22 17:30:50,107 https://limitswap.gitbook.io/limitswap/
INFO: 2021-04-22 17:30:50,107 *************************************************************************************
INFO: 2021-04-22 17:30:50,872 Here is Latest Release Version  on Github Please Make Sure You are Staying Updated = v2.9363
INFO: 2021-04-22 17:30:52,232 Current Tokens Staked = 52.0
INFO: 2021-04-22 17:30:52,232 Trader Price = 50 Tokens Staked
INFO: 2021-04-22 17:31:05,659 ***********************************************************
INFO: 2021-04-22 17:31:05,659 Please Use Github & Telegram to ask about Buy Errors Below:
INFO: 2021-04-22 17:31:05,659 ***********************************************************
ERROR: 2021-04-22 17:31:05,659 'tx'
Traceback (most recent call last):
  File "main.py", line 280, in buy
KeyError: 'tx'
ERROR: 2021-04-22 17:31:05,659 {'statusCode': 500, 'message': 'Not enough allowance. Amount: 10000000000000000. Allowance: 0. Spender: 0x11111112542d85b3ef69ae05771c2dccff4faa26', 'error': 'Internal Server Error'}
INFO: 2021-04-22 17:31:07,435 ***********************************************************
INFO: 2021-04-22 17:31:07,435 Please Use Github & Telegram to ask about Buy Errors Below:
INFO: 2021-04-22 17:31:07,435 ***********************************************************
ERROR: 2021-04-22 17:31:07,435 'tx'
Traceback (most recent call last):
  File "main.py", line 280, in buy
KeyError: 'tx'
ERROR: 2021-04-22 17:31:07,435 {'statusCode': 500, 'message': 'Not enough allowance. Amount: 10000000000000000. Allowance: 0. Spender: 0x11111112542d85b3ef69ae05771c2dccff4faa26', 'error': 'Internal Server Error'}
INFO: 2021-04-22 17:31:10,600 ***********************************************************
INFO: 2021-04-22 17:31:10,601 Please Use Github & Telegram to ask about Buy Errors Below:
INFO: 2021-04-22 17:31:10,601 ***********************************************************
ERROR: 2021-04-22 17:31:10,601 'tx'
Traceback (most recent call last):
  File "main.py", line 280, in buy
KeyError: 'tx'
ERROR: 2021-04-22 17:31:10,602 {'statusCode': 500, 'message': 'Not enough allowance. Amount: 10000000000000000. Allowance: 0. Spender: 0x11111112542d85b3ef69ae05771c2dccff4faa26', 'error': 'Internal Server Error'}

https://media.discordapp.net/attachments/763150064826712094/834847202831499294/Screen_Shot_2021-04-22_at_7.44.36_AM.png?width=699&height=592

P.S. I hope there's something we can do to eliminate the struggle in calculating the listing price on listing..

**Comment by Asian-Cutie** [comment]
@CryptoGnome

**Comment by CryptoGnome** [comment]
deprecated
