### ISSUE TITLE
StackOS PCS Listing Issue

### ISSUE THREAD

**Issue by lainof** [CryptoGnome/LimitSwap#165]
Got this error trying to snipe in the StackOS PCS listing:

KeyError: 'tx'
ERROR: 2021-04-23 16:10:51,904 {'statusCode': 500, 'message': 'cannot find path for 0x6855f7bb6287F94ddcC8915E37e73a3c9fEe5CF3', 'error': 'Internal Server Error'}
INFO: 2021-04-23 16:10:53,404 ***********************************************************
INFO: 2021-04-23 16:10:53,404 Please Use Github & Telegram to ask about Buy Errors Below:
INFO: 2021-04-23 16:10:53,404 ***********************************************************
ERROR: 2021-04-23 16:10:53,404 'tx'
Traceback (most recent call last):
  File "main.py", line 280, in buy
KeyError: 'tx'
ERROR: 2021-04-23 16:10:53,419 {'statusCode': 500, 'message': 'cannot find path for 0x6855f7bb6287F94ddcC8915E37e73a3c9fEe5CF3', 'error': 'Internal Server Error'}

Tokens.json file:
[
 {
  "SYMBOL": "STACK",
  "ADDRESS": "0x6855f7bb6287F94ddcC8915E37e73a3c9fEe5CF3",
  "BASESYMBOL": "BUSD",
  "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
  "BUYAMOUNT": "500",
  "MAXAMOUNT": "35000",
  "BUYPRICE": "0.225",
  "SELLAMOUNT": "ALL",
  "SELLPRICE": "0.375",
  "MOONBAG": "0",
  "SLIPPAGE": "49",
  "GAS": "300",
  "LIQUIDITYCHECK": "FALSE",
  "LIQUIDTYWBNB": "50"
  }
]

**Comment by CryptoGnome** [comment]
this was migration issue
