### ISSUE TITLE
Feature request | percentage feature in moonbag/sellamount

### ISSUE THREAD

**Issue by Asian-Cutie** [CryptoGnome/LimitSwap#166]
Hi Devs,

can we have an additional feature that would allow us to set the moonbag in percentage instead of specific number?
example: MOONBAG: "20%", ( this % is against the total of what you are going to sell)

Otherwise, we can we set the "SELLAMOUNT": "25%,50%,75% or 100%", instead "ALL" - if we can make this, we can disregard the first request since the purpose is just the same.

Looking forward for your response on this. TIA @CryptoGnome @koyabya

**Comment by CryptoGnome** [comment]
this will not be supported
