### ISSUE TITLE
Feature Request: Move slippage to token.json (or override?)

### ISSUE THREAD

**Issue by sidework** [CryptoGnome/LimitSwap#17]
I am trying to sell an unnamed token that has a super high sales tax. 99% of the time I would want slippage under 1%, but to sell this token I need slippage at closer to 15%. I had it set to 15, forgot, and got killed on two trades because of the slippage. It would be nice to set this at the token, or perhaps have an override on the token to override the setting.json setting.

**Comment by smartins** [comment]
That's a good suggestion, second it.

**Comment by jondoeog** [comment]
Good idea, there are tokens when I just do regular scalping with lower slippage and some others with stinky bids/asks that would allow higher slippage play. Having set slippage custom to each token would be a great enhancement.

**Comment by jondoeog** [comment]
Other idea for improvement is being able to set **different** **slippage** for **buys** and **sells**.

Reason behind it is front running bots, when I have 5%+ slippage, even when I snipe something, there is bot that bought before me with +0.000001 gwei and sold the same amount of tokens with -.000001 less gwei, draining some ETH from me.
Today I had for instance slippage set to 10.5
I was about to buy token for 0.0131   limitswap got front-run by another bot that drained liquidity from me.
In the end I got my trade executed at 0.0147. Immediate loss of 10%+.

Solution for that would be ability to set low slippage for **buy** i.e 2-3% and high slippage for **sell** (10%+) as if bot doesn't have tokens, he can't drain liquidity and sell order we might want to execute "at all cost" while buy not necessarily.

**Comment by CryptoGnome** [comment]
added in v3
