### ISSUE TITLE
KeyError: 'toTokenAmount'

### ISSUE THREAD

**Issue by schmidtlogistic** [CryptoGnome/LimitSwap#170]
hy i have a problem
I am using the bot for the first time
and get the error message

'toTokenAmount'
Traceback (most recent call last):
  File "main.py", line 532, in <module>
  File "main.py", line 519, in auth
  File "main.py", line 467, in run_pro
  File "main.py", line 381, in quote_usd
KeyError: 'toTokenAmount'
'toTokenAmount'

I have a token because I just want to sell, not buy

[
 {
  "SYMBOL": "AIRMOON",
  "ADDRESS": "0xe4dc901b801e3238b885f8bcac55e74fd621f8e9",
  "BASESYMBOL": "WBNB",
  "BASEADDRESS": "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c",
  "BUYAMOUNT": "0",
  "MAXAMOUNT": "0",
  "BUYPRICE": "1",
  "SELLAMOUNT": "ALL",
  "SELLPRICE": "0.000000000300000",
  "MOONBAG": "0",
  "SLIPPAGE": "15",
  "GAS": "5",
  "LIQUIDITYCHECK": "TRUE",
  "LIQUIDTYWBNB": "100"
  }
]

**Comment by CryptoGnome** [comment]
deprecated
