### ISSUE TITLE
Some tokens are not supported BSC

### ISSUE THREAD

**Issue by schmidtlogistic** [CryptoGnome/LimitSwap#171]
![image](https://user-images.githubusercontent.com/57215214/116385557-2eef1000-a819-11eb-8d5b-e812317a2bfe.png)

**Comment by schmidtlogistic** [comment]
this is my config
I already have AIRMOON in my wallet and just want to sell

[
 {
  "SYMBOL": "AIRMOON",
  "ADDRESS": "0xe4dc901b801e3238b885f8bcac55e74fd621f8e9",
  "BASESYMBOL": "WBNB",
  "BASEADDRESS": "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c",
  "BUYAMOUNT": "0.000001",
  "MAXAMOUNT": "0",
  "BUYPRICE": "0.000000000000001",
  "SELLAMOUNT": "ALL",
  "SELLPRICE": "0.000000000000570",
  "MOONBAG": "0",
  "SLIPPAGE": "15",
  "GAS": "5",
  "LIQUIDITYCHECK": "TRUE",
  "LIQUIDTYWBNB": "100"
  }
]

**Comment by CryptoGnome** [comment]
deprecated
