### ISSUE TITLE
Bot shows incorrect pricing and wild fluctuations, whereas live market data is relatively stable

### ISSUE THREAD

**Issue by bishalu** [CryptoGnome/LimitSwap#172]
See title. This happened with all of WBNB, BUSD and BNB as the base pairs. Here's an excerpt from the program:

Current Liquidity Reserves: 1324232598289.837 WBNB                                                                      Max Position Reached for FORESTRY Skipping Token                                                                        Current Price FORESTRY = 1.12013509007E-7 BNB                                                                           Buy Signal Found for FORESTRY                                                                                           FORESTRY Current Wallet Balance is : 6.149754767                                                                        BNB Current Wallet Balance is : 0.0                   

Current Liquidity Reserves: 1324232598289.837 WBNB                                                                      Max Position Reached for FORESTRY Skipping Token                                                                        Current Price FORESTRY = 1.12013509007E-7 BNB                                                                           Buy Signal Found for FORESTRY                                                                                           FORESTRY Current Wallet Balance is : 6.149754912                                                                        BNB Current Wallet Balance is : 0.0                                                                                    

 Current Liquidity Reserves: 1324222038299.2524 WBNB                                                                     Max Position Reached for FORESTRY Skipping Token                                                                        Current Price FORESTRY = 1.12013509007E-7 BNB                                                                           Buy Signal Found for FORESTRY                                                                                           FORESTRY Current Wallet Balance is : 6.149754912                                                                        BNB Current Wallet Balance is : 0.0                                                                                     

Current Liquidity Reserves: 1324222038299.2524 WBNB                                                                     Max Position Reached for FORESTRY Skipping Token                                                                        Current Price FORESTRY = 1.12013509007E-7 BNB                                                                           Buy Signal Found for FORESTRY                                                                                           FORESTRY Current Wallet Balance is : 6.149754912                                                                        BNB Current Wallet Balance is : 0.0                                                                                     

Current Liquidity Reserves: 1324222038299.2524 WBNB                                                                     Max Position Reached for FORESTRY Skipping Token                                                                        Current Price FORESTRY = 1.12013509007E-7 BNB                                                                           Buy Signal Found for FORESTRY                                                                                           FORESTRY Current Wallet Balance is : 6.149780527                                                                        BNB Current Wallet Balance is : 0.0                                                                                     

Current Liquidity Reserves: 1319966265707.3242 WBNB                                                                     Max Position Reached for FORESTRY Skipping Token                                                                        Current Price FORESTRY = 2.0433361887459E-7 BNB                                                                         Buy Signal Found for FORESTRY                                                                                           FORESTRY Current Wallet Balance is : 6.149866106                                                                        BNB Current Wallet Balance is : 0.0                                                                                     

Current Liquidity Reserves: 1319966265707.3242 WBNB                                                                     Max Position Reached for FORESTRY Skipping Token                                                                        Current Price FORESTRY = 2.9634432501165E-7 BNB                                                                         Buy Signal Found for FORESTRY                                                                                           FORESTRY Current Wallet Balance is : 6.149914282                                                                        BNB Current Wallet Balance is : 0.0                                                                                     Current Liquidity Reserves: 1319752025303.8662 WBNB                                                                     Max Position Reached for FORESTRY Skipping Token                                                                        Current Price FORESTRY = 2.9634432501165E-7 BNB                                                                         Buy Signal Found for FORESTRY                                                                                           FORESTRY Current Wallet Balance is : 6.149914282                                                                        BNB Current Wallet Balance is : 0.0                                                                                     

Current Liquidity Reserves: 1319752025303.8662 WBNB                                                                     Max Position Reached for FORESTRY Skipping Token                                                                        Current Price FORESTRY = 2.9634432501165E-7 BNB                                                                         Buy Signal Found for FORESTRY                                                                                           FORESTRY Current Wallet Balance is : 6.149914282
                                                                        BNB Current Wallet Balance is : 0.0                                                                                     
Current Liquidity Reserves: 1319752025303.8662 WBNB                                                                     Max Position Reached for FORESTRY Skipping Token                                                                        Current Price FORESTRY = 2.9634432501165E-7 BNB                                                                         Buy Signal Found for FORESTRY                                                                                           FORESTRY Current Wallet Balance is : 6.149914282
                                                                        BNB Current Wallet Balance is : 0.0                                                                                     Current Liquidity Reserves: 1319752025303.8662 WBNB                                                                     Max Position Reached for FORESTRY Skipping Token                                                                        Current Price FORESTRY = 2.9634432501165E-7 BNB                                                                         Buy Signal Found for FORESTRY                                                                                           FORESTRY Current Wallet Balance is : 6.149914282                                                                        BNB Current Wallet Balance is : 0.0                                                                                                                                                                      

Current Liquidity Reserves: 1313434687161.023 WBNB                                                                      Max Position Reached for FORESTRY Skipping Token                                                                        Current Price FORESTRY = 4.0694468349503E-7 BNB       

The bot also bought at a higher prices than intended. 
Could the time zone be a factor?

**Comment by CryptoGnome** [comment]
fixed in v3
