### ISSUE TITLE
BETA - IMPROVEMENT IDEA - add "-" character every 2 lines

### ISSUE THREAD

**Issue by tsarbuig** [CryptoGnome/LimitSwap#176]
t's difficult to see how bot is fast, or if it's working, when all the lines keep the same price

My idea is to put an "-" at the end of every 2 lines

Instead of : 
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC

Write : 
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC -
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC -
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC -
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC -
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC -
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC -
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC -
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC -
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC -
GLASS  Price $ 5.813649141e-09 USDC
GLASS  Price $ 5.813649141e-09 USDC -

Like this, people will see that new lines are appearing

**Comment by CryptoGnome** [comment]
![image](https://user-images.githubusercontent.com/33667144/116693134-77c6d600-a98b-11eb-88ec-f28dfcb993a8.png)

**Comment by CryptoGnome** [comment]
Using timestamps instead
