### ISSUE TITLE
BETA - IMPROVEMENT request: MAXTOKENS currently calculates based off of WEI, should be something else

### ISSUE THREAD

**Issue by D-B-S-G** [CryptoGnome/LimitSwap#178]
**Issue**-"MAXTOKENS": "#.#" should not buy additional tokens when current token balance is higher than that number.

Reproducible bug on 5 different coins so far. Need improvement, currently MAXTOKENS is value in WEI (https://eth-converter.com/)

**Token.Json example (the only thing that changes is "MAXTOKENS") :**

Forestry: **ONE** buy request at 0.001BNB gives 11336203 FORESTRY (Confirmed in wallet)

[
  {
  "SYMBOL": "Forestry",
  "ADDRESS": "0x8c5a93fa9bb2b0f396e80b51323767043c58e686",
  "BASESYMBOL": "WBNB",
  "BASEADDRESS": "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c",
  "BUYAMOUNTINBASE": "0.001",
  "BUYPRICEINBASE": "1",
  "SELLAMOUNTINTOKENS": "ALL",
  "SELLPRICEINBASE": "1",
  "MAXTOKENS": "0.00001",
  "MOONBAG": "0",
  "SLIPPAGE": "39",
  "HASFEES": "true",
  "GAS": "50",
  "BOOSTPERCENT": "50",
  "GASLIMIT": "300000"
  }
]

Forestry: **EIGHT** more buy requests at 0.001BNB, new total 101505785 FORESTRY (Confirmed in wallet)

[
  {
  "SYMBOL": "Forestry",
  "ADDRESS": "0x8c5a93fa9bb2b0f396e80b51323767043c58e686",
  "BASESYMBOL": "WBNB",
  "BASEADDRESS": "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c",
  "BUYAMOUNTINBASE": "0.001",
  "BUYPRICEINBASE": "1",
  "SELLAMOUNTINTOKENS": "ALL",
  "SELLPRICEINBASE": "1",
  "MAXTOKENS": "0.1",
  "MOONBAG": "0",
  "SLIPPAGE": "39",
  "HASFEES": "true",
  "GAS": "50",
  "BOOSTPERCENT": "50",
  "GASLIMIT": "300000"
  }
]

**Comment by CryptoGnome** [comment]
Fixed
