### ISSUE TITLE
gas limit usage issue

### ISSUE THREAD

**Issue by kobiek** [CryptoGnome/LimitSwap#18]
script will keep trying to endlessly buy even if it doesn't hit the gas limit level required to buy certain pairs. User will sustain heavy gas fees on fail Txs. 

![chrome_W19fKFBHMv](https://user-images.githubusercontent.com/73394456/97084245-c746d680-15e3-11eb-96d3-b72608a005ee.png)

**Comment by CryptoGnome** [comment]
Added Sanity check for 3 txs, after that will blacklist
