### ISSUE TITLE
LOG IMPROVEMENT : when you enter a wrong private key

### ISSUE THREAD

**Issue by tsarbuig** [CryptoGnome/LimitSwap#180]
when you enter a shitty private key, you have this error message : 

ERROR: 2021-04-30 22:14:26,308 Non-hexadecimal digit found
Traceback (most recent call last):
  File "LimitSwap.py", line 674, in <module>
  File "LimitSwap.py", line 199, in auth

please add a comment "There is a problem with your private key : please check if it's correct. Don't enter seed phrase !"

**Comment by CryptoGnome** [comment]
i need full log

**Comment by CryptoGnome** [comment]
added
