### ISSUE TITLE
IMPROVEMENT: Make the sell price a multiple of the buy price

### ISSUE THREAD

**Issue by koopkapital** [CryptoGnome/LimitSwap#189]
Using the bot, it will be easier if we could set the sell price to be a multiple of the buy price. 
So lets say the BUYPRICEINBASE was set at 1. the bot executes and buys as long as the price is less than 1.  in this example, lets say the bot buys in the market at 0.5.

There should be a field: SELL_PRICE_MULTIPLE that is in the range [0, inf] that allows the bot to multiply BUYPRICEINBASE by SELL_PRICE_MULTIPLE. This way we introduce less human error and can be more certain on return parameters.

**Comment by CryptoGnome** [comment]
you can just do that math, we are not adding more options then needed as it only complicates things. hence why we rolled back to a more basic settings library.
