### ISSUE TITLE
IMPROVEMENT idea about BASE pair

### ISSUE THREAD

**Issue by tsarbuig** [CryptoGnome/LimitSwap#197]
I've been thinking about this BNB / WBNB issue, and I think I've found an elegant solution

**Current situation**
it's confusing for users, as they choose WBNB base pair, and bot trades with BNB

**My solution**
use new parameters : 

USECUSTOMBASEPAIR : 'false',
CUSTOMBASESYMBOL : 'enter here your custom Base pair symbol if you set True'
CUSTOMBASEADDRESS : 'enter here your custom Base pair address if you set True'

- if it's set to "false" the bot uses BNB / ETH / etc. --> bot uses swapExactTokensForTokens
- if it's set to "true", bot does not use swapExactTokensForTokens anymore, and people can trade with WBNB

what do you think of it ?

```
[
  {
  "SYMBOL": "KPAD",
  "ADDRESS": "0xcfefa64b0ddd611b125157c41cd3827f2e8e8615",

  "USECUSTOMBASEPAIR" : 'true',
  "CUSTOMBASESYMBOL": "BUSD",
  "CUSTOMBASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",

  "BUYAMOUNTINBASE": "100",
  "BUYPRICEINBASE": "3.9",
  "SELLAMOUNTINTOKENS": "ALL",
  "SELLPRICEINBASE": "4.3",

  "MAXTOKENS": "1",
  "MOONBAG": "0",
  "SLIPPAGE": "5",
  "HASFEES": "false",

  "GAS": "5",
  "BOOSTPERCENT": "10",
  "GASLIMIT": "300000",

  "LIQUIDITYCHECK": "false",
  "LIQUIDITYAMOUNT": "10"  
  }
]
```

**Comment by CryptoGnome** [comment]
added 0.04
