### ISSUE TITLE
NEED A BASE PAIR ADDRESS ALWAYS - check error log attached

### ISSUE THREAD

**Issue by koopkapital** [CryptoGnome/LimitSwap#199]
[errors.log](https://github.com/CryptoGnome/LimitSwap/files/6415360/errors.log)

"USECUSTOMBASEPAIR": "false", - even if you set this field to False, you still need to enter the base name and address. does not default to BNB it seems (Pancakeswap)

**Comment by CryptoGnome** [comment]
fixed
