### ISSUE TITLE
Check balance for USECUSTOMBASEPAIR = true checks BNB instead of custom base token

### ISSUE THREAD

**Issue by pandalearns** [CryptoGnome/LimitSwap#201]
Version: 3.06

For the following scenarios, here's my wallet balance:

BNB: 0.1
WBNB: 0.8

### Scenario 1:

[
  {
  "SYMBOL": "BUSD",
  "ADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
  **"USECUSTOMBASEPAIR": "true",**
  "BASESYMBOL": "WBNB",
  "BASEADDRESS": "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c",
  "BUYAMOUNTINBASE": "0.3",
  "BUYPRICEINBASE": "0.002",
  "SELLAMOUNTINTOKENS": "ALL",
  "SELLPRICEINBASE": "10",
  "MAXTOKENS": "1",
  "MOONBAG": "0",
  "SLIPPAGE": "1",
  "HASFEES": "true",
  "GAS": "20",
  "BOOSTPERCENT": "0",
  "GASLIMIT": "500000",
  "LIQUIDITYCHECK": "false",
  "LIQUIDITYAMOUNT": "10"
  }
]

I have enough WBNB in my balance since that is what I want to buy with but the balance check for BASE token checks on my BNB balance instead.

Error message
INFO: 2021-05-03 17:03:20,732 BuySignal Found @0.000000000001315646
INFO: 2021-05-03 17:03:20,889 Not Enough Balance in BASE token to make buys
INFO: 2021-05-03 17:03:21,685 BuySignal Found @0.000000000001315646
INFO: 2021-05-03 17:03:21,826 Not Enough Balance in BASE token to make buys
INFO: 2021-05-03 17:03:22,607 BuySignal Found @0.000000000001315646
INFO: 2021-05-03 17:03:22,748 Not Enough Balance in BASE token to make buys
INFO: 2021-05-03 17:03:23,529 BuySignal Found @0.000000000001315646
INFO: 2021-05-03 17:03:23,670 Not Enough Balance in BASE token to make buys
INFO: 2021-05-03 17:03:24,482 BuySignal Found @0.000000000001297767
INFO: 2021-05-03 17:03:24,623 Not Enough Balance in BASE token to make buys
INFO: 2021-05-03 17:03:25,404 BuySignal Found @0.000000000001297767

### Scenario 2:

[
  {
  "SYMBOL": "BUSD",
  "ADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
  **"USECUSTOMBASEPAIR": "true",**
  "BASESYMBOL": "WBNB",
  "BASEADDRESS": "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c",
  "BUYAMOUNTINBASE": "0.01",
  "BUYPRICEINBASE": "0.002",
  "SELLAMOUNTINTOKENS": "ALL",
  "SELLPRICEINBASE": "10",
  "MAXTOKENS": "1",
  "MOONBAG": "0",
  "SLIPPAGE": "1",
  "HASFEES": "true",
  "GAS": "20",
  "BOOSTPERCENT": "0",
  "GASLIMIT": "500000",
  "LIQUIDITYCHECK": "false",
  "LIQUIDITYAMOUNT": "10"
  }
]

This one, I tried buying with WBNB with enough amount of BNB i have but I got a totally different error:

INFO: 2021-05-04 00:18:27,921 BuySignal Found @0.001497132458691295
ERROR: 2021-05-04 00:18:28,171 Python int too large to convert to C ssize_t
Traceback (most recent call last):
  File "LimitSwap.py", line 663, in run
  File "LimitSwap.py", line 444, in buy
  File "web3\contract.py", line 954, in call
  File "web3\contract.py", line 1507, in call_contract_function
  File "eth_abi\codec.py", line 181, in decode_abi
  File "eth_abi\decoding.py", line 127, in __call__
  File "eth_utils\functional.py", line 45, in inner
  File "eth_abi\decoding.py", line 173, in decode
  File "eth_abi\decoding.py", line 127, in __call__
  File "eth_abi\decoding.py", line 144, in decode
  File "eth_abi\decoding.py", line 95, in push_frame
  File "eth_abi\decoding.py", line 84, in seek_in_frame
OverflowError: Python int too large to convert to C ssize_t
ERROR: 2021-05-04 00:18:28,171 Python int too large to convert to C ssize_t
Traceback (most recent call last):

### Scenario 3:

[
  {
  "SYMBOL": "BUSD",
  "ADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
  **"USECUSTOMBASEPAIR": "false",**
  "BASESYMBOL": "WBNB",
  "BASEADDRESS": "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c",
  "BUYAMOUNTINBASE": "0.01",
  "BUYPRICEINBASE": "0.002",
  "SELLAMOUNTINTOKENS": "ALL",
  "SELLPRICEINBASE": "10",
  "MAXTOKENS": "1",
  "MOONBAG": "0",
  "SLIPPAGE": "1",
  "HASFEES": "true",
  "GAS": "20",
  "BOOSTPERCENT": "0",
  "GASLIMIT": "500000",
  "LIQUIDITYCHECK": "false",
  "LIQUIDITYAMOUNT": "10"
  }
]

This is the only thing that worked for me so far, I was able to buy with BNB and skipped buying WBNB overall

Log files:

[exceptions.log](https://github.com/CryptoGnome/LimitSwap/files/6418679/exceptions.log)
[errors.log](https://github.com/CryptoGnome/LimitSwap/files/6418681/errors.log)

**Comment by CryptoGnome** [comment]
fixed next release
