### ISSUE TITLE
Improvement : show token name after  "Sell signal found" and "Placing sell order"

### ISSUE THREAD

**Issue by tsarbuig** [CryptoGnome/LimitSwap#202]
<img width="716" alt="Capture d’écran 2021-05-04 à 10 59 57" src="https://user-images.githubusercontent.com/70858574/116981539-ed061400-acc7-11eb-9342-f3a8b08ea47b.png">

add token name here for sell and for buy orders

example : "Sell signal found" --> "Sell signal found for BSCPAD"

I can seem redundant, but it's important for people playing with several tokens at the same time

**Comment by CryptoGnome** [comment]
next release
