### ISSUE TITLE
Log improvement : add token name after "Current Wallet balance"

### ISSUE THREAD

**Issue by tsarbuig** [CryptoGnome/LimitSwap#203]
<img width="600" alt="Capture d’écran 2021-05-04 à 15 16 16" src="https://user-images.githubusercontent.com/70858574/117009284-dd002b80-aceb-11eb-9a54-38b02d92d837.png">

"Current Wallet balance is" --> "Current BNB Wallet balance is"

**Comment by CryptoGnome** [comment]
fixed next version
