### ISSUE TITLE
Issue buying with BUSD

### ISSUE THREAD

**Issue by skimit604** [CryptoGnome/LimitSwap#208]
I have no problem buying with WBNB but have issue with buying BUSD on pancakeswap; the transaction will not go through but will not create an error or exception; I see on my bscscan

[Fail with error 'Pancake: TRANSFER_FAILED'] 
[Warning! Error encountered during contract execution [execution reverted] 

Here is my tokens.json

"SYMBOL": "CHEE",
  "ADDRESS": "0x93e24685e41ca82fd7a66a69c64f3decac789281",
  
  "USECUSTOMBASEPAIR": "true",
  "BASESYMBOL": "BUSD",
  "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
  "BUYAMOUNTINBASE": "5",
  "BUYPRICEINBASE": "0",
  
  
  "SELLAMOUNTINTOKENS": "ALL",
  "SELLPRICEINBASE": "1000",
  
  
  "MAXTOKENS": "1",
  "MOONBAG": "0",
  "SLIPPAGE": "49",
  "HASFEES": "true",
  "GAS": "5",
  "BOOSTPERCENT": "0",
  "GASLIMIT": "500000",
  
  
  "LIQUIDITYCHECK": "false",
  "LIQUIDITYAMOUNT": "0.04"
  }
]

I have tried hasfees true and false; I have tried buying the token with busd manually on pancake and it goes through; and finally I have tried buying the token with WBNB with limitswap and it works no problem. But when I try to buy with BUSD through limitswap, the transaction fails.

**Comment by CryptoGnome** [comment]
post the tx here

**Comment by skimit604** [comment]
https://bscscan.com/address/0xE84c56EAdba5ba418e92016Ae70B9E4F4a7363eC

You can see all my failed transactions on my wallet

**Comment by skimit604** [comment]
ya, I tried with other tokens with busd and it worked; just doesn't work with this specific coin for some reason. This likely isn't a limitswap issue.
