### ISSUE TITLE
Successful buying but never a successful sell

### ISSUE THREAD

**Issue by cjbutcher** [CryptoGnome/LimitSwap#210]
Every sell order I've ever made through LimitSwap (v3.10) is failing with the likes of 'TRANSFER_FROM_FAILED' or 'Pancake K' or similar. From the Telegram I understand several other users are having the same issue.

I usually buy relatively new coins going through large price fluctuations, where slippage would be important. I make sure there is about 10 BNB in liquidity before buying however.

Performing the same sells manually works fine. It is almost like LimitSwap is ignoring the slippage setting on sell (I have it at 49).

I will comment an example tokens.json that I am using below.

**Comment by cjbutcher** [comment]
Example trade (failed with error 'TransferHelper: TRANSFER_FROM_FAILED')

[
  {
    "SYMBOL": "POOROCKET",
    "ADDRESS": "0x2ed990dce85f30951d1bc26676ed0a5fcbdc12d2",
    "USECUSTOMBASEPAIR": "false",
    "BASESYMBOL": "WBNB",
    "BASEADDRESS": "0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c",
    "BUYAMOUNTINBASE": "0.1",
    "BUYPRICEINBASE": "0.0000000000000000000000000000001",
    "SELLAMOUNTINTOKENS": "ALL",
    "SELLPRICEINBASE": "0.0000000000000000000000000000001",
    "MAXTOKENS": "1",
    "MOONBAG": "0",
    "SLIPPAGE": "49",
    "HASFEES": "false",
    "GAS": "7",
    "BOOSTPERCENT": "50",
    "GASLIMIT": "300000",
    "LIQUIDITYCHECK": "true",
    "LIQUIDITYAMOUNT": "20"
  }
]

**Comment by CryptoGnome** [comment]
link the tx please

**Comment by cjbutcher** [comment]
Hi @CryptoGnome, here it is: https://bscscan.com/tx/0x18d23afbfe6b13045527e7cb4394e8cdad8ddabeed967072bb80414e9a010e7b

Lots of transactions failed on that address at they are all LimitSwap related. I am now trying with an 800000 gas as we speak and I will let you know if its better.

**Comment by cjbutcher** [comment]
Raising the gas didn't work. More failed transactions listed on the address. The suceessful sells were all done manually.

**Comment by CryptoGnome** [comment]
this is a as limit issue fixing in next release
