### ISSUE TITLE
pangolin - failed transaction of swapping a token

### ISSUE THREAD

**Issue by disip23** [CryptoGnome/LimitSwap#211]
Hello mate! Good Day!

I tried using Limitswap bot version 3.10 on pangolin. I tried buying SNOB (Snowball) tokens and it failed. Could you check on this issue? my hunch is that the issue is coming from this type of swapping. The bot always use 'SwapExactETHForTokens' which I think should be 'SwapExactAVAXForTokens'. 

Also to add another issue I found. the approval of limitswap bot for every tokens at the very first second sometimes fail. As per testing and analyzing, the bot only APPROVE the contract of the token if it is:

Bot Only approve:
- if the parameters in 'Write Contract' are "spender(address)" and "amount(uint256)" (example token used here is SNOB)

Bot Will Not approve:
- if the parameters in 'Write Contract' are "spender(address)" and "rawAmount(uint256)", etc...... so basically the bot Will Not approve the contract of the tokens if the parameters are not default (like above). (example token used here is PNG)

Let me know if you need more details. :) Glad to help for improvements

See screenshots below for references.

![BotOnlyApprove](https://user-images.githubusercontent.com/54366530/117458876-56627d00-af7d-11eb-86ff-a79c53410a5e.png)

![BotDoesNotApprove](https://user-images.githubusercontent.com/54366530/117458836-4a76bb00-af7d-11eb-8003-09aa3ae2c0f8.png)

![SwapExactETHForTokens](https://user-images.githubusercontent.com/54366530/117459565-1ea80500-af7e-11eb-97fb-f5133f331505.png)

![SwapExactAVAXForTokens](https://user-images.githubusercontent.com/54366530/117459582-22d42280-af7e-11eb-8452-8e5c632c7291.png)

**Comment by CryptoGnome** [comment]
fixed
