### ISSUE TITLE
Bot is only reporting liquidity status for 1 coin when having 2 x tokens in tokens.json, both tokens yet to launch on pancake

### ISSUE THREAD

**Issue by bobby4star** [CryptoGnome/LimitSwap#213]
Hi CryptoGnome,
Trying to line up the bot to buy on 2 x tokens set to launch today.    The bot has properly done the approve transactions and checks them when launching bot.   But it only reports  "Not Listed For Trade Yet... waiting for liquidity to be added on exchange" 
  for the first token.     It does not report this for the 2nd token.     Is it a bug as only checking 1 of the coins?     

in the tokens.json i have as follows;-

  {
    "SYMBOL": "DIAMONDHOLD",
    "ADDRESS": "0xdea00cbb3804d478d6cacd35a3781383858f6e2f",
    "USECUSTOMBASEPAIR": "true",
    "BASESYMBOL": "BUSD",
    "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
    "BUYAMOUNTINBASE": "100",
    "BUYPRICEINBASE": "0.05",
    "SELLAMOUNTINTOKENS": "ALL",
    "SELLPRICEINBASE": "10",
    "MAXTOKENS": "1000000",
    "MOONBAG": "0",
    "SLIPPAGE": "49.9999",
    "HASFEES": "false",
    "GAS": "10",
    "BOOSTPERCENT": "0",
    "GASLIMIT": "300000",
    "LIQUIDITYCHECK": "true",
    "LIQUIDITYAMOUNT": "0.3"
  },
  {
    "SYMBOL": "HYPERGALAXY",
    "ADDRESS": "0x5115849ee5b70e717a1069e50b52a59d4ee42fbc",
    "USECUSTOMBASEPAIR": "true",
    "BASESYMBOL": "BUSD",
    "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
    "BUYAMOUNTINBASE": "100",
    "BUYPRICEINBASE": "0.08",
    "SELLAMOUNTINTOKENS": "ALL",
    "SELLPRICEINBASE": "10",
    "MAXTOKENS": "1000",
    "MOONBAG": "0",
    "SLIPPAGE": "49.9999",
    "HASFEES": "false",
    "GAS": "10",
    "BOOSTPERCENT": "0",
    "GASLIMIT": "300000",
    "LIQUIDITYCHECK": "true",
    "LIQUIDITYAMOUNT": "0.3"
  }

Thanks

**Comment by CryptoGnome** [comment]
The bot is only able to do snipe mode with one token
