### ISSUE TITLE
Pangolin - try to approve WAVAX even it have been successfully approved before

### ISSUE THREAD

**Issue by lausam88** [CryptoGnome/LimitSwap#217]
Hi, recently I am messing around with the bot and try to buy PNG on Pangolin, during the process, I change the token setting for a few time, then I find out the bot try to approve WAVAX again, even it have been approved before, it didnt happen everything time I change the setting.

P.S. I also encounter the same issue for pangolin mentioned in issue 211, keep up the good work :)

**Comment by CryptoGnome** [comment]
fixed
