### ISSUE TITLE
IMPROVEMENT - Check if we can liquidity added in BUSD

### ISSUE THREAD

**Issue by tsarbuig** [CryptoGnome/LimitSwap#218]
Hi, some users reported that bot does not detect liquidity added in BUSD 

Can you check if it's possible to add it without reducing bot speed ?

Thanks

**Comment by chrispincer** [comment]
> Hi, some users reported that bot does not detect liquidity added in BUSD
> 
> Can you check if it's possible to add it without reducing bot speed ?
> 
> Thanks

Yes Please mister Gnome i  want this too .!!

**Comment by CryptoGnome** [comment]
unable to support this, the contract throws errors as it usually is looking for BNB
