### ISSUE TITLE
Quickswap can't find liquidity

### ISSUE THREAD

**Issue by picesszaza** [CryptoGnome/LimitSwap#221]
Hi i have some problem with Quickswap i'm tesed can buy same pair with Quickswap but bot show "Not listed for trade yet..."

**Comment by AJolly** [comment]
To be more specific: Limitswap only can start trading if there is liquidity on the native base pair, not a custom base pair.
2) Limit swap only uses the native base pair, not the custom for pricing.
3) Doesnt take into account slippage when calculating pricing
