### ISSUE TITLE
An error occurred after the purchase was successful.

### ISSUE THREAD

**Issue by lovelynoise** [CryptoGnome/LimitSwap#225]
![1](https://user-images.githubusercontent.com/37989679/118398503-e7c7a280-b693-11eb-8f71-484d4684ce1f.jpg)
![2](https://user-images.githubusercontent.com/37989679/118398506-e9916600-b693-11eb-98d8-472be3bae22b.jpg)
![3](https://user-images.githubusercontent.com/37989679/118398509-ea29fc80-b693-11eb-9761-c1b06ed3a2d5.jpg)
Error, but successed buy token aleady.
transactions.json empty.

**Comment by CryptoGnome** [comment]
try using a custom node, sometimes this happens when network is congested and tx never makes it through
