### ISSUE TITLE
BUY ERROR

### ISSUE THREAD

**Issue by Bhunakit** [CryptoGnome/LimitSwap#234]
Even though the bot received the buy signal, it did not buy successfully. 
This is the tx: https://bscscan.com/tx/0xdf6c4b98cc6fb8aff00c26f97d8c06fb7ceb9aa048eb8dea8cbc9f1bad963643

Error Log:
INFO: 2021-05-18 19:54:14,588 BuySignal Found @0.000000000000027816
INFO: 2021-05-18 19:54:50,442 NO BUY FOUND, WE WILL CHECK A FEW TIMES TO SEE IF THERE IS BLOCKCHAIN DELAY, IF NOT WE WILL ASSUME THE TX HAS FAILED
INFO: 2021-05-18 19:54:51,158 BuySignal Found @0.000000000000028508
INFO: 2021-05-18 19:55:26,029 NO BUY FOUND, WE WILL CHECK A FEW TIMES TO SEE IF THERE IS BLOCKCHAIN DELAY, IF NOT WE WILL ASSUME THE TX HAS FAILED
INFO: 2021-05-18 19:55:26,740 BuySignal Found @0.000000000000036087
INFO: 2021-05-18 19:56:02,319 NO BUY FOUND, WE WILL CHECK A FEW TIMES TO SEE IF THERE IS BLOCKCHAIN DELAY, IF NOT WE WILL ASSUME THE TX HAS FAILED
INFO: 2021-05-18 19:56:03,038 BuySignal Found @0.000000000000038497
INFO: 2021-05-18 19:56:38,315 NO BUY FOUND, WE WILL CHECK A FEW TIMES TO SEE IF THERE IS BLOCKCHAIN DELAY, IF NOT WE WILL ASSUME THE TX HAS FAILED
INFO: 2021-05-18 19:56:39,025 BuySignal Found @0.000000000000044680
INFO: 2021-05-18 19:57:14,435 NO BUY FOUND, WE WILL CHECK A FEW TIMES TO SEE IF THERE IS BLOCKCHAIN DELAY, IF NOT WE WILL ASSUME THE TX HAS FAILED

Config:
[
  {
  "SYMBOL": "DINGO",
  "ADDRESS": "0x397e6d4fd68a9e25e93fc712b8f72f826f48a8ff",
  
  "USECUSTOMBASEPAIR": "false",
  "BASESYMBOL": "",
  "BASEADDRESS": "",
  "BUYAMOUNTINBASE": "0.02",
  "BUYPRICEINBASE": "1",
  
  
  "SELLAMOUNTINTOKENS": "ALL",
  "SELLPRICEINBASE": "1",
  
  
  "MAXTOKENS": "100000000000000",
  "MOONBAG": "0",
  "SLIPPAGE": "49",
  "HASFEES": "true",
  "GAS": "15",
  "BOOSTPERCENT": "0",
  "GASLIMIT": "250000",
  
  
  "LIQUIDITYCHECK": "false",
  "LIQUIDITYAMOUNT": "10"
  }
]

**Comment by CryptoGnome** [comment]
price was moving to fast to buy
