### ISSUE TITLE
Cannot sell or buy anything.

### ISSUE THREAD

**Issue by Kriemhild123** [CryptoGnome/LimitSwap#239]
Version: 3.11
Settings (also tried several nodes and private node):
        "USECUSTOMNODE": "false",
        "CUSTOMNODE": "",
        "EXCHANGE": "pancakeswap",
		"EXCHANGEVERSION": "2",
		"PREAPPROVE": "true"
    }
Tokens (for selling):
[
  {
  "SYMBOL": "BUSD",
  "ADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
  
  "USECUSTOMBASEPAIR": "true",
  "BASESYMBOL": "WBNB",
  "BASEADDRESS": "0xbb4cdb9cbd36b01bd1cbaebf2de08d9173bc095c",
  "BUYAMOUNTINBASE": "0.0001",
  "BUYPRICEINBASE": "0",
  
  
  "SELLAMOUNTINTOKENS": "ALL",
  "SELLPRICEINBASE": "0",
  
  
  "MAXTOKENS": "0.00001",
  "MOONBAG": "0",
  "SLIPPAGE": "25",
  "HASFEES": "true",
  "GAS": "40",
  "BOOSTPERCENT": "0",
  "GASLIMIT": "500000",
  
  
  "LIQUIDITYCHECK": "false",
  "LIQUIDITYAMOUNT": "10"
  }
]

Errors:
INFO: 2021-05-21 12:54:54,690 Current Tokens Staked = 50.0
INFO: 2021-05-21 12:54:54,690 YOUR BOT IS CURRENTLY RUNNING VERSION 3.11
INFO: 2021-05-21 12:54:54,993 Checking Latest Release Version on Github, Please Make Sure You are Staying Updated = v3.11
INFO: 2021-05-21 12:54:55,477 Sell Signal Found @0.002606909324039897
INFO: 2021-05-21 12:55:56,270 Transaction Timed Out, Breaking Check Cycle....
INFO: 2021-05-21 12:55:56,644 Sell Signal Found @0.002606317326156699

Execptions:
None

**Comment by CryptoGnome** [comment]
This i have tested and is working, please trey new release today... also you have "HASFEES": "true", when neither of these two tokens has fees... it should be false
