### ISSUE TITLE
Fail with error 'PancakeRouter: INSUFFICIENT_OUTPUT_AMOUNT'

### ISSUE THREAD

**Issue by tomek01992** [CryptoGnome/LimitSwap#240]
I had all the time this errors. Its not once, but everytime i try to buy tokens i bought it after few fails, 1-10 fails.

https://bscscan.com/tx/0xe4e8cd4cab938a1cf7a7e086974ba42dc81c790337e7b4733740456f6881f7fc

"SLIPPAGE": "49",
  "HASFEES": "true",
  "GAS": "100",
  "BOOSTPERCENT": "0",
  "GASLIMIT": "800000",
  
  
  "LIQUIDITYCHECK": "false",
  "LIQUIDITYAMOUNT": "0"

**Comment by CryptoGnome** [comment]
slippage is more than your value
