### ISSUE TITLE
Limit for buy / sell 

### ISSUE THREAD

**Issue by tomek019** [CryptoGnome/LimitSwap#243]
Could you set up in futures version limit for quantity of transactions ? For example 1 transaction for buy, than if it will be failed or sucess (Whatever), bot will not make any new transactions for buy. This same can be be for sell.

**Comment by ChapzyX** [comment]
+1 @CryptoGnome please add this function urgently instead of MAXTOKEN "1", as we need 1 Time Selling function as well. Thanks
