### ISSUE TITLE
Unable (unstable) to check liquidity of token

### ISSUE THREAD

**Issue by khuenguyennhu** [CryptoGnome/LimitSwap#245]
Hello,

I'm using the bot. At the beginning, it could check liquidity and the price.
Suddenly (around 4 minutes), it couldn't do that and show "Not listed....waiting for liquidity....).
If I closed it and tried to run again, it could show the error "Binance Smart Chain Connected = False"
In some case, it could run again but face the error after some minutes.

I added all the info (tokens.json, screenshot,...) [here](https://1drv.ms/u/s!ApzRoRxKkk5yi8NMODA0uOaOCOSZVg?e=GY106L)

Please help to check and give me some advice to fix this issue.

Thanks and Regards,
Kenny

**Comment by khuenguyennhu** [comment]
Today, I did many tests and I might get the root cause of the issue. It seems the bot was blocked due to many requests per second (around 16).  It will be blocked after around 4 minutes.
I added the [screenshot](https://1drv.ms/u/s!ApzRoRxKkk5yi8NXYHlCFw0fXusT4A?e=8urypR) and [bot_screen](https://1drv.ms/t/s!ApzRoRxKkk5yi8NWOyiMfuMhSrINlA?e=fRczRG) file for your info.
I tried with slower PC (around 4 queries/second) the issue didn't happen. So please help to check if we could control the number of queries per second and we could get the best suitable speed.

Thanks and Regards,
Kenny

**Comment by CryptoGnome** [comment]
you can use your own node, or custom node
