### ISSUE TITLE
No Buy Found

### ISSUE THREAD

**Issue by Ojay4real** [CryptoGnome/LimitSwap#250]
During a launch  when the bot tries to buy it comes back w
[error log.txt](https://github.com/CryptoGnome/LimitSwap/files/6554686/error.log.txt)
ith "No Buy found........."

I currently have 10 limits and use gas: 120, slippage: 49%.

Attached is the error, log and Settings.

<img width="627" alt="No Buy Found" src="https://user-images.githubusercontent.com/59031515/119842759-dfc2fa80-befe-11eb-9e9d-7769569e6679.PNG">

<img width="559" alt="setting" src="https://user-images.githubusercontent.com/59031515/119842770-e0f42780-befe-11eb-8e97-88c8f1ab9655.PNG">

[error log.txt](https://github.com/CryptoGnome/LimitSwap/files/6554700/error.log.txt)

**Comment by CryptoGnome** [comment]
was there a transaction???

**Comment by alexpo** [comment]
Hi. May be problem in settings? error log.txt file include -"INFO: 2021-05-24 09:29:08,739 There is a problem with your private key : please check if it's correct. Don't enter seed phrase !"

"PRIVATEKEY": "private key for wallet you want to trade on",
