### ISSUE TITLE
Add feature to do multiple buy at the same time | BSC

### ISSUE THREAD

**Issue by manz30** [CryptoGnome/LimitSwap#251]
Since almost all of new degens have small max buy amount so we need to buy multiple time to have large amount of the tokens
on this screenshot i tried run 2 limitswap.exe at the same time with same configuration of tokens.json and its generated same tx hash so its only 1 buy order

i tried run with different tokens.json also but the 1st transaction got dropped/replaced by the 2nd one, i guess its because the first one not yet confirmed and the 2nd tx got same nonce as the first one

hope you can find the solution, very need this feature

![photo_2021-05-30_19-02-30](https://user-images.githubusercontent.com/32212947/120199890-e67aa600-c24d-11eb-8181-0fa754652ba8.jpg)

**Comment by manz30** [comment]
or add option customize nonce in the token.json so i just need run multiple bot with custom nonce for each bot

**Comment by CryptoGnome** [comment]
this will not be supported.
