### ISSUE TITLE
It keeps buying and selling if the price difference is low

### ISSUE THREAD

**Issue by dex224** [CryptoGnome/LimitSwap#252]
Hello, 
Even if the max tokens = 1, it keep selling and after that buying and repeat these 2 operations until I have no money to pay fees.
![1](https://user-images.githubusercontent.com/84903083/120212786-153b5100-c23b-11eb-8531-fa7907698786.png)

Thank you !

**Comment by CryptoGnome** [comment]
please show/link the transactions

**Comment by dex224** [comment]
![image](https://user-images.githubusercontent.com/84903083/120888916-7e3c1380-c603-11eb-8843-2919c42c1552.png)
![image](https://user-images.githubusercontent.com/84903083/120888918-8005d700-c603-11eb-9d1d-2b397aaab2d4.png)
![image](https://user-images.githubusercontent.com/84903083/120888919-81cf9a80-c603-11eb-8cd2-c2d9c98a4824.png)
![image](https://user-images.githubusercontent.com/84903083/120888922-83995e00-c603-11eb-91fd-1e5786690f1f.png)

**Comment by dex224** [comment]
I read wiki, I am on telegram group for a few weeks and read everything you or Tsar post but as I`ve said earlier, the bot is selling and after that is buying again and again these 2 operations  until I have no money left ( max tokens = 1 ).

Thank you very much for this app, 

Sorry to bother you

**Comment by dex224** [comment]
buying : 

![image](https://user-images.githubusercontent.com/84903083/120889074-323d9e80-c604-11eb-9cfa-d5b42f62c4e7.png)
![image](https://user-images.githubusercontent.com/84903083/120889077-34076200-c604-11eb-9c72-11c8098a38c5.png)

**Comment by dex224** [comment]
another txn`s

![image](https://user-images.githubusercontent.com/84903083/120889895-0e7c5780-c608-11eb-9924-95239ef384e8.png)
![image](https://user-images.githubusercontent.com/84903083/120889896-11774800-c608-11eb-8ef4-1e2c0c6b8b47.png)
![image](https://user-images.githubusercontent.com/84903083/120889898-163bfc00-c608-11eb-8a28-a2124d5d6bc1.png)
![image](https://user-images.githubusercontent.com/84903083/120889900-189e5600-c608-11eb-9c8c-5eacf798337f.png)
![image](https://user-images.githubusercontent.com/84903083/120889901-1b994680-c608-11eb-98bb-208b6d74ec57.png)
![image](https://user-images.githubusercontent.com/84903083/120889903-1e943700-c608-11eb-91fc-5989bd8d09ef.png)
![image](https://user-images.githubusercontent.com/84903083/120889904-20f69100-c608-11eb-9898-d5f7e0bc58e0.png)
![image](https://user-images.githubusercontent.com/84903083/120889906-2522ae80-c608-11eb-806b-f3b501e15585.png)

**Comment by dex224** [comment]
First photo of me showing you the problem is a different token but with the same settings as TopCat.

**Comment by alexpo** [comment]
Hi. You buy more expensive than you sell - is it planned? SELL 5839 < BUY 5841 . Sells immediately after purchase and will never stop
