### ISSUE TITLE
Problem with Custom Node

### ISSUE THREAD

**Issue by DDDeal** [CryptoGnome/LimitSwap#255]
There is a problem with the use of custom node, I can‘t use a ws:node. If I disable preApprove it’s more or less working and it shows „liquidity not found“ message but can’t buy even when there is liq. There is most likely a fault in the web3 implementation.

error.txt showing me this when preApprove is true:
requests.exceptions.InvalidSchema: No connection adapters were found for 'ws://92.130*************'
ERROR: No connection adapters were found for 'ws://92.130*************'

**Comment by CryptoGnome** [comment]
only http supported
