### ISSUE TITLE
Newest version incorrectly calculates ETH gas fees with "boost" applied

### ISSUE THREAD

**Issue by jondoeog** [CryptoGnome/LimitSwap#258]
This are my settings:
part from settings.json

        "USECUSTOMNODE": "false",
        "CUSTOMNODE": "put your own node here if you want and make, USECUSTOMNODE = TRUE",
        "EXCHANGE": "uniswap",
		"EXCHANGEVERSION": "2",
		"PREAPPROVE": "false",
		"UNLIMITEDSLIPPAGE": "false"

part from tokens.json

  "GAS": "boost",
  "BOOSTPERCENT": "7",
  "GASLIMIT": "250000",

Currently on blockchain was ~17 gwei as rapid.
Bot submitted transaction with 6.42 gwei:

![image](https://user-images.githubusercontent.com/74243437/120887330-6ad47c80-c5f2-11eb-9263-e82410ab97bd.png)

**Comment by CryptoGnome** [comment]
we pull the info from the exact block when checking, this is correct use a bigger boost to counteract this, I am also adding a check in new  version

**Comment by jondoeog** [comment]
Cmon, Ethereum Rapid couldn't show 6 gwei at any point in time when at the time fees were 12-20 gwei..not possible.

**Comment by CryptoGnome** [comment]
100% it calculates in the correct block, it can fluctuate drastically

**Comment by jondoeog** [comment]
I was in front of computer when it happened and gwei was ~16
I have constantly this page opened:
https://www.gasnow.org/

The lowest gwei is on Sundays, and even then I hardly ever see "Slow" one below 8..7-8 is the lowest I have seen. Let alone rapid 6 on ETH network when I was monitoring it live.

**Comment by CryptoGnome** [comment]
gas now is an algo, it is not the true gas price returned by the blockchain

**Comment by CryptoGnome** [comment]
we no longer use gasnow, we are reading on chain prices, some changes were made in 3.14 to help with this
