### ISSUE TITLE
Not selling all the tokens in one txn

### ISSUE THREAD

**Issue by dex224** [CryptoGnome/LimitSwap#260]
![1](https://user-images.githubusercontent.com/84903083/121043258-20ebc200-c7bd-11eb-83cc-36873c43fef0.png)
![2](https://user-images.githubusercontent.com/84903083/121043261-221cef00-c7bd-11eb-9a69-23ed4d61df8d.png)
![3](https://user-images.githubusercontent.com/84903083/121043269-22b58580-c7bd-11eb-8cee-ad7271aea9be.png)

**Comment by CryptoGnome** [comment]
some tokens with taxes will take a few sells, will stop when the decimals are lower
