### ISSUE TITLE
Absolute Path

### ISSUE THREAD

**Issue by alphaai** [CryptoGnome/LimitSwap#261]
![Screen Shot 2021-06-09 at 2 03 01 am](https://user-images.githubusercontent.com/2101080/121220846-57faca00-c8c8-11eb-81e9-e3f131d7c7bd.png)

**Comment by CryptoGnome** [comment]
rename the sub folder if you want o label, not the top folder

**Comment by alphaai** [comment]
I am trying to run my app ive built which uses your bot and I cannot
because the working directory is not using the absolute path. 

https://help.pythonanywhere.com/pages/NoSuchFileOrDirectory
