### ISSUE TITLE
price not calculated correctly (uniswap v2 bug?)

### ISSUE THREAD

**Issue by chasdabigone** [CryptoGnome/LimitSwap#262]
I put this token in: 0xE6C3502997f97F9BDe34CB165fBce191065E068f
i have specified uniswap version 2 in the settings (the liquidity is on v2)
The price is calculated incorrectly. Perhaps it is pulling from v3?
![Capture](https://user-images.githubusercontent.com/13225826/121444156-8faf5380-c954-11eb-8440-1a3dcd5752e8.PNG)

**Comment by chasdabigone** [comment]
![tokens](https://user-images.githubusercontent.com/13225826/121577247-f5501e00-c9ee-11eb-8217-c7adc596f63a.PNG)

**Comment by CryptoGnome** [comment]
this is correct it pulls the wbtc price as that is your base pair. uniswap v3 is not supported yet

**Comment by chasdabigone** [comment]
hi it is listing KBTC as $2.00 when i put USDC as the base pair, or an
extremely small number when I put the base pair as WBTC. That is not
correct as it is about 0.79 WBTC right now. Look on uniswap v2 it is
trading 0.79 WBTC not a few dollars.
