### ISSUE TITLE
I failed snipe

### ISSUE THREAD

**Issue by resatakkus** [CryptoGnome/LimitSwap#263]
Today, I tried to get "Demodify", which was made on ido Bscpad. I could not get the bot even though I opened the bot half an hour before the start and entered the codes in this way. But he bought many other wallets from me and with higher amounts.
My tokens json.
[
  {
    "SYMBOL": "DMOD",
    "ADDRESS": "0x002d8563759f5e1eaf8784181f3973288f6856e4",

    "USECUSTOMBASEPAIR": "false",
    "BASESYMBOL": "false",
    "BASEADDRESS": "false",
    "BUYAMOUNTINBASE": "1",
    "BUYPRICEINBASE": "1000",

    "SELLAMOUNTINTOKENS": "ALL",
    "SELLPRICEINBASE": "2",

    "MAXTOKENS": "0.00001",
    "MOONBAG": "0",
    "SLIPPAGE": "49",
    "HASFEES": "true",
    "GAS": "20",
    "BOOSTPERCENT": "0",
    "GASLIMIT": "1000000",

    "LIQUIDITYCHECK": "true",
    "LIQUIDITYAMOUNT": "100"
  }

  
]
I made the sale price high. To sell manually
A lot of crash tx all same https://bscscan.com/tx/0x29b1064f659144bb5853a3aedb42a2ea85a7d5440f6969a729a63e4e59d74ac9
![photo_2021-06-10_21-39-05](https://user-images.githubusercontent.com/48046647/121579400-5bab5f80-ca34-11eb-8725-24ef2e24a11f.jpg)
![1](https://user-images.githubusercontent.com/48046647/121579402-5c43f600-ca34-11eb-9490-a0dff7fd8d18.jpg)
![photo_2021-06-10_21-39-03](https://user-images.githubusercontent.com/48046647/121579405-5cdc8c80-ca34-11eb-9b26-706f923c2534.jpg)
![photo_2021-06-10_21-39-00](https://user-images.githubusercontent.com/48046647/121579406-5cdc8c80-ca34-11eb-8453-bc158c44898a.jpg)

**Comment by alexpo** [comment]
Hi. Bon Appetit everyone;) 
This site BSCPAD launches **_anti-bot protection_**. You hit it. You can read more details in the official channel BSCPAD
Those who were able to buy are banned on the IDO site.
**### _The problem is not with the script._** I myself got 3 times on this. Note that the number of tokens is also limited to no more than 2000. and after 3 minutes there is no such thing. In large projects, there is protection.
