### ISSUE TITLE
Selling a token on MATIC Quickswap results in "Fail with error 'Quick::approve: amount exceeds 96 bits"

### ISSUE THREAD

**Issue by Napkinss** [CryptoGnome/LimitSwap#266]
When selling QUICK token on quick swap, the TX fails with the error "'Quick::approve: amount exceeds 96 bits"

The bot does the pre approval, checks for approval status. It continues to check pride and place the sell order. However it keeps failing and the bot will continue to keep checking the price and placing the sell order.

Failed Approval TX Hash: 0x83970a301f1a10f597eaca77dd207b13452e18ff7435c06ddcd26ffd292d6beb
Failed Sell Order TX Hash: 0x593f731b664d0712eb2344c584ca6174a40618a89dbb78d4a2901b24bcc64f84
Settings:
<img width="607" alt="lim2" src="https://user-images.githubusercontent.com/85951274/122081002-4fa70f80-ce31-11eb-86ce-9fb6a9816ecf.png">

Bot:
![lim1](https://user-images.githubusercontent.com/85951274/122080580-f4751d00-ce30-11eb-9280-43b053302b20.jpg)

<img width="673" alt="LIM3" src="https://user-images.githubusercontent.com/85951274/122081272-8d0b9d00-ce31-11eb-8072-51a8392a1ba8.png">

Polyscan:
![image](https://user-images.githubusercontent.com/85951274/122084362-571be800-ce34-11eb-820b-3cad56df1e61.png)
![image](https://user-images.githubusercontent.com/85951274/122084579-86caf000-ce34-11eb-8c30-a34a8f20f359.png)

**Comment by Napkinss** [comment]
Manually approving and selling from the website works

**Comment by CryptoGnome** [comment]
is this the only token you have seen this on?

**Comment by CryptoGnome** [comment]
resolved in new release

**Comment by ZRiddle** [comment]
Found this issue on other tokens.
This is the problematic code:
```
    function safe96(uint n, string memory errorMessage) internal pure returns (uint96) {
        require(n < 2**96, errorMessage);
        return uint96(n);
    }
```

So the approval amount has to be less than 2^96, or 10^28 if you are using powers of 10:
```
>>> 2**96 < 1e28
False
>>> 2**96 < 1e29
True
```
