### ISSUE TITLE
Failed Executions trying to sell with bot

### ISSUE THREAD

**Issue by rafaelmocelin** [CryptoGnome/LimitSwap#267]
I have tried selling two different tokens with the bot and I got failed transactions, which started eating up my gas.

I then tried to sell both tokens manually, with same gas and slippage and it worked.

The buying works fine.

I'm attaching screenshots of the settings of the bot and the transactions.

![Screen Shot 2021-06-16 at 09 13 05](https://user-images.githubusercontent.com/7683588/122216790-21eab680-ce83-11eb-864d-e6b1b1d711b0.png)

![Screen Shot 2021-06-16 at 09 14 45](https://user-images.githubusercontent.com/7683588/122216934-4fcffb00-ce83-11eb-9651-54e8c76d1114.png)

![Capture](https://user-images.githubusercontent.com/7683588/122218458-da652a00-ce84-11eb-8619-aee6747ba743.PNG)

![Capture2](https://user-images.githubusercontent.com/7683588/122218481-df29de00-ce84-11eb-9e38-80631601c3f2.PNG)

**Comment by CryptoGnome** [comment]
please link the transaction

**Comment by CryptoGnome** [comment]
try making hasfees = true
