### ISSUE TITLE
BOOST + 50% 

### ISSUE THREAD

**Issue by ceej0103** [CryptoGnome/LimitSwap#269]
I used the bot to get in to a position the other day using the BOOST setting with 50% boost.  When the buy price was achieved, the purchase was made no problem. The screenshot shows the gas paid. 

When it came time to sell, the bot initiated the transaction but offered virtually no gas to ensure the transaction went through quickly.  IIRC, the estimated gas was $.06 on the transaction. Luckily I was near the computer and could manually sell the position.  

![image](https://user-images.githubusercontent.com/86087729/122492691-38dcf600-cfb4-11eb-8cfe-7fdedd47fbc6.png)

**Comment by CryptoGnome** [comment]
fixed next release
