### ISSUE TITLE
the bot couldn't make buy with usdt

### ISSUE THREAD

**Issue by Shane20088** [CryptoGnome/LimitSwap#274]
hi, I set my base pair as USDT and the bot showed my balance 3000+ USDT,but I could't make a 500U buy. It said I do not have enough balance to make buy. but when I swtiched it back to ETH, it worked fine. Pls check it out.
![image](https://user-images.githubusercontent.com/86467776/123399716-87ebe200-d5d7-11eb-8ba9-229923b5a8d7.png)
![image](https://user-images.githubusercontent.com/86467776/123399733-8de1c300-d5d7-11eb-84cd-0241607940ee.png)
![image](https://user-images.githubusercontent.com/86467776/123399746-92a67700-d5d7-11eb-815f-87d06c685666.png)

**Comment by CryptoGnome** [comment]
i cannot reproduce this, you must have another error in your settings
