### ISSUE TITLE
Bot spends long time on Approval process before being able to check price

### ISSUE THREAD

**Issue by c133** [CryptoGnome/LimitSwap#276]
Note: TG user "Peter" reports that 3.13 works just fine, while 3.15 has the approval delay bug. (3.14 also has the bug from my experience)

1st example:

![image](https://user-images.githubusercontent.com/5353882/123479947-40f5f080-d5c7-11eb-8e5a-a7ab1112187a.png)
![image](https://user-images.githubusercontent.com/5353882/123479972-4a7f5880-d5c7-11eb-9b2e-50dfc0fa7466.png)

2nd example:

![image](https://user-images.githubusercontent.com/5353882/123480260-b366d080-d5c7-11eb-88c4-e315d3acb0a1.png)
![image](https://user-images.githubusercontent.com/5353882/123480271-b9f54800-d5c7-11eb-9060-eb6fff7c85a4.png)

Gas settings:
![image](https://user-images.githubusercontent.com/5353882/123480749-6d5e3c80-d5c8-11eb-9937-f16acfa3d7a1.png)
100 gwei

So I tested on 3.15 latest version, opening the bot with a uniswap coin, it will try to approve the coin but always takes very long time for some reason before approval goes through and then the bot starts checking the price. I'm wondering if I'm doing something wrong or if there is a bug. Basically I want the bot to approve as quickly as possible so that it can check price asap so that I can buy. Thanks Gnome!

**Comment by CryptoGnome** [comment]
fixed
