### ISSUE TITLE
.....Waiting.... Approval bug still exists in 3.17

### ISSUE THREAD

**Issue by c133** [CryptoGnome/LimitSwap#277]
Tested in 3.17 and the approval waiting bug still exists for me. Tested on two different coins. 

My steps:

1. Edit token settings, paste a new coin address, save
2. Run the bot

![image](https://user-images.githubusercontent.com/5353882/123869850-2a1d0a00-d8f7-11eb-88c9-f90429151bc0.png)
![image](https://user-images.githubusercontent.com/5353882/123869868-2e492780-d8f7-11eb-97f9-3209090b4b0f.png)
![image](https://user-images.githubusercontent.com/5353882/123869980-4f117d00-d8f7-11eb-916d-68f228bf0fa0.png)

Also included my settings here, let me know if something here is causing this. Gas was ~30 and I set gas to 100 in settings.
Thanks @CryptoGnome

**Comment by ccollector11** [comment]
I have the same issue. It is so frustrating.

**Comment by CryptoGnome** [comment]
this should be resolved
