### ISSUE TITLE
Issues with Sniper Bot v0.17

### ISSUE THREAD

**Issue by Lukas12111** [CryptoGnome/LimitSwap#282]
I tried 3 times sniping on BSC today with the new sniper bot v.0.17. I have 100 Limit tokens.
1st Contract was at 20UTC on 07/03/21(22:00h in europe time);
tokens.json looked like this:
[
  {
    "ADDRESS": "0x86EB590eF1E2C3a74536DbeBB9d3967c5cC282F7",
    "SYMBOL": "Game of Thrones Token",
    "BUYAMOUNT": "0.013",
	"MULTIPLEBUYS": "false",
    "BUYCOUNT": "5",
	 "RUGCHECK": "false"

  }
]

The Bot started, detected that i had 100 limit tokens. Than it scanned for Liquidity for a while. Then when the Token launched, the Bot detected Liquidity, made a buy Transaction, but the Transaction failed. Then the Bot closed itself automatically. Unfortunately i cannot see the Txn Hash anymore. Not in the Erros file or in the BSCscan of my Adress. The only thing what i can read in the Error file is ;
INFO: 2021-07-02 21:47:48,540 Current $LIMIT Tokens Staked = 100.77674846268785
INFO: 2021-07-02 22:00:34,070 Buy Sent Stopping Bot
But it never bought the Token. The Token by the way was a scam. So i am not disapointed lol. But it was just a try..therefore not much bnb.

2nd and 3rd Token i tried with diffferent tokens.json:
[
  {
    "ADDRESS": "0x326E1d2D9e7F8F3a4Df13766Aa3B3AeF33546546",
    "SYMBOL": "GrandpaDoge",
    "BUYAMOUNT": "0.013",
	"MULTIPLEBUYS": "true",
    "BUYCOUNT": "2",
	 "RUGCHECK": "true"

  }
]
and
[
  {
    "ADDRESS": "0x0084a178606dbd8e25796109244ca17f8abc35a6",
    "SYMBOL": "Nigiri",
    "BUYAMOUNT": "0.01",
	"MULTIPLEBUYS": "false",
    "BUYCOUNT": "2",
	 "RUGCHECK": "false"

  }
]
Both had the same Problem; The Bot was searching for Liquidity...but it never saw Liquidity, Even 5 Minutes after the Launch of both Tokens...the Bot never detected Liquidity. So it never bought. And both Tokens wer flying at the beginning. 

In my Settings i have different Adresses for Limitwallet and the Wallet i want to buy with...but that was never the Problem with the Normal Bot with 50 tokens. Maybe that was my Problem.
Also i had "USECUSTOMNODE": "false".

Maybe i could help to make the Bot better. Would be insane if we have a good mempool Bot.

**Comment by kakao789** [comment]
was the first one launching presale on DXsale ? i tried the sniper on the last 2 and didnt work for me either. Maybe DXsale adds liqudity in a different way and that's why it doesnt detects the liqudity add transaction

**Comment by kakao789** [comment]
made a video about the liqudity detect issue. i was running the sniper and limit swap next to eachother. this token had dxsale presale and started from there. i was running the bots on VPS using sniper v0.14 (having this issue on V0.17 aswell).

0x615FEc1e184F72A0EBf8611df339b08D32B5b05F
https://youtu.be/I7vDNwjdTco

**Comment by Lukas12111** [comment]
I don't really remember the first coin...and it was a scam... so i can't find it anymore because their Telegram is deleted. But i think there was no presale. The second Coin "GrandpaDoge" and 3rd Coin "Nigiri"....both of them had Presales on DxSale, yes. And on both it didn't detected Liquidity just like in your Video. But the most important Coins for me have presales on DxSale...so i hope CryptoGnome can fix this in the next Version. By the way nice Video. I am sure this helps the Dev finding the bugs and correct them.

**Comment by CryptoGnome** [comment]
bot does not work on dx sale or tokens with bot protect ie: 
```
interface IPancakeRouter02 is IPancakeRouter01 {
    function removeLiquidityETHSupportingFeeOnTransferTokens(
        address token,
        ```
        
in the contract at the moment, we are working on dx sale support

**Comment by CryptoGnome** [comment]
Please open a new ticket requesting DxSale support and I will keep it updated on the sniper github here:
https://github.com/CryptoGnome/Limit-Sniper
