### ISSUE TITLE
Sniper bot v0.17 don’t saw a liquidity 

### ISSUE THREAD

**Issue by Slylee85** [CryptoGnome/LimitSwap#285]
I tried a snipe coin SEED
CA 0x4bc6e19ee0f1e034a927990c76b418c2a95e326f

developers told what an anti bot built in to the contract. 
if you can pls check the CA to improve sniper bot with the anti Antibot system )))))
Thx to you guys. You’re the best.

**Comment by CryptoGnome** [comment]
it worked for me, did you get  a failed tx?

**Comment by Slylee85** [comment]
I’ve tried to snipe that coin with limit sniper. And sniper don’t saw an add liquidity event ((((
