### ISSUE TITLE
ValueError: Could not find any function with matching selector

### ISSUE THREAD

**Issue by NachoJSBSC** [CryptoGnome/LimitSwap#287]
[errors.log](https://github.com/CryptoGnome/LimitSwap/files/6766060/errors.log)
[Uploading errors.log…]()

**Comment by NachoJSBSC** [comment]
[
  {
    "ADDRESS": "0x41B6F618dE653ACC304ADbA150b61aEA72f5252A",
    "SYMBOL": "SFE",
    "BUYAMOUNT": "0.1",
	"MULTIPLEBUYS": "true",
    "BUYCOUNT": "10",
	 "RUGCHECK": "true"

  }
]

**Comment by CryptoGnome** [comment]
did any of that transactions buy?

**Comment by CryptoGnome** [comment]
also please send me bsc link to the failed tx

**Comment by NachoJSBSC** [comment]
Hi, no transaction bought.

https://bscscan.com/tx/0xc8ef45b3298d1d806437f55f0ee77d8f09774538fbd3425e7de62a462475f5a2
https://bscscan.com/tx/0x9d3945453c1bc4be03c2826ce2a71dc21e3e8ba642ab31d976d5514b00492036

**Comment by CryptoGnome** [comment]
this contract had max tx size and your buy was to big
```
require(amounts[0] <= amountInMax, 'PancakeRouter: EXCESSIVE_INPUT_AMOUNT');
```

**Comment by NachoJSBSC** [comment]
0.1 bnb is too much? what value would you recommend max?
