### ISSUE TITLE
Sniper Bot Failed to See Liquidity Addition & Place Buy Order

### ISSUE THREAD

**Issue by CryptoGeno** [CryptoGnome/LimitSwap#289]
Sniper bot v0.17 was running ~15 minutes prior to liquidity being added, when liquidity was added it failed to detect and place a buy order. Just kept scanning for liquidity.

Token: SafeLaunch
Contract: 0x41b6f618de653acc304adba150b61aea72f5252a
Telegram group for more launch/token info: https://t.me/SafeLaunch_IO

**Comment by CryptoGnome** [comment]
launchpad, bot will not detect this, same a dx sale atm
