### ISSUE TITLE
Add a maxPriceImpact variable for those cases where there's very little uniswap liquidity

### ISSUE THREAD

**Issue by smartins** [CryptoGnome/LimitSwap#29]
There are cases where there's very little initial liquidity for a pair (usually when it's added by someone other than the team).

For example, for nsure, which did a dutch-auction on balancer, users who bough there already have tokens and someone added very little liquidity to uniswap. Official team list will be later.

If we try to sell for example 5000 tokens (~1300 usd), there will be a 30% price impact. Having a variable for the maximum price impact would allow to add a pair to sell and be sure that we won't incur a significant "loss" of gains because of the price impact.

![image](https://user-images.githubusercontent.com/396734/97706593-da5b1a00-1aad-11eb-97eb-8304e7f63e75.png)

**Comment by CryptoGnome** [comment]
This is already implemented as far as I know, it is called slippage, that is what you circled

**Comment by smartins** [comment]
SLIPPAGE from settings.json? Isn't that the sell slippage? Or is there a SLIPPAGE variable that can be added to each individual entry on tokens.json?

**Comment by CryptoGnome** [comment]
Yes this is what slippage is it is moving to tokens in the next release
