### ISSUE TITLE
Can not snipe on new launches

### ISSUE THREAD

**Issue by dex224** [CryptoGnome/LimitSwap#291]
Hello, The bot is seeing the liquidity, but i can`t buy. Lose my bnb in fees.
In settings , unlimited slippage : true

![b](https://user-images.githubusercontent.com/84903083/124641412-5a385000-de97-11eb-87fd-64358768aa06.png)
![c](https://user-images.githubusercontent.com/84903083/124641414-5ad0e680-de97-11eb-9c87-36a71330ef91.png)
![a](https://user-images.githubusercontent.com/84903083/124641416-5ad0e680-de97-11eb-9f54-2cafaf5c4d7b.png)

**Comment by CryptoGnome** [comment]
price moving to fast, you can try using unlimited slippage if the launch is popular
