### ISSUE TITLE
Can't trade on Kuswap

### ISSUE THREAD

**Issue by logoscrypt** [CryptoGnome/LimitSwap#294]
When trying to buy a token that is already being traded, the limitswap does not see liquidity. I have already checked with many coins, it does not help.

![Безымянный](https://user-images.githubusercontent.com/87063564/124723573-df614a80-df13-11eb-85c6-db2db2d51447.png)
![2](https://user-images.githubusercontent.com/87063564/124723578-dff9e100-df13-11eb-8c07-a90b9c9d85d0.png)
![3](https://user-images.githubusercontent.com/87063564/124723580-e0927780-df13-11eb-8749-6c7800d9bfb2.png)

**Comment by CryptoGnome** [comment]
investigating today!

**Comment by CryptoGnome** [comment]
fixed
