### ISSUE TITLE
LimitSwap Bot buying issue

### ISSUE THREAD

**Issue by yangyanhh** [CryptoGnome/LimitSwap#297]
Using in MATIC chain QUICKSWAY,For example,I have 10000 token in my wallet and i set the MAXTOKENS 5000,at first it indicate Max Position Size Reached and no buying ,but minutes later it shows wait wait wait and keep buying...
See below screenshot
https://imgur.com/iZNQFq9

**Comment by yangyanhh** [comment]
Just test and happened again.I have 9083316 TITAN in my wallet ,and set the  "MAXTOKENS as 1000,and i found the bot will detect wrongly the wallet balance as 0,so will find the buy signal and buy it.See below
https://imgur.com/NltvnkH

**Comment by CryptoGnome** [comment]
this is a node issue
