### ISSUE TITLE
Approve problem on ETH

### ISSUE THREAD

**Issue by jondoeog** [CryptoGnome/LimitSwap#299]
Using 3.21 (newest available version).

I have pre-approve option selected to false. In old version bot would then approve token, whenever it has a balance and want to do transaction. Pre-approve as TRUE would approve right away.

With 3.21 and FALSE selected, bot doesn't try to approve at all. It just spams transactions and try to sell without ever approving the token (obviously it will keep failing). Had 10 failed tx and luckily was on computer and got notifications, otherwise bot would drain my ETH account to 0...You need some fail switch man, this is dangerous stuff.

![image](https://user-images.githubusercontent.com/74243437/125056148-39931480-e0a8-11eb-836a-936ffa26ccf5.png)

This was the error, when I approved token manually it started working.

![image](https://user-images.githubusercontent.com/74243437/125056221-4e6fa800-e0a8-11eb-907f-2a45691d5e12.png)

**Comment by CryptoGnome** [comment]
I see I will add a check to sell when preapprove is false
