### ISSUE TITLE
Insufficient Balance. Had 0

### ISSUE THREAD

**Issue by edblak** [CryptoGnome/LimitSwap#3]
Running Pro on v2.43. Metamask has sufficient balance (0.2647 ETH) to cover the buy parameters set in tokens.json.
![IMAGE 2020-10-12 03:45:08](https://user-images.githubusercontent.com/28668861/95688506-5562aa80-0c3d-11eb-8310-317f886184f0.jpg)
INFO - 2020-10-12 03:25:13,403 - Starting Pro Bot
ERROR - 2020-10-12 03:25:19,397 - Insufficient balance. Had 0, needed 2647177770154034000
Traceback (most recent call last):
  File "limitswap.py", line 320, in start_bot
  File "limitswap.py", line 277, in start_many
  File "limitswap.py", line 143, in run_bot
  File "limitswap.py", line 232, in buy
  File "uniswap\uniswap.py", line 69, in approved
  File "uniswap\uniswap.py", line 430, in make_trade
uniswap.uniswap.InsufficientBalance: Insufficient balance. Had 0, needed 2647177770154034000
INFO - 2020-10-12 03:25:22,165 - Starting Pro Bot

tokens.json
-----------
[
    {
        "ADDRESS": "0x15bcdfad12498de8a922e62442ae4cc4bd33bd25",
        "SYMBOL": "WALT",
        "BUYPRICE": 0.044,
        "SELLPRICE": 0.2398,
        "MAXTOKENS": 1800,
        "BUYAMOUNT": 1000,
        "STOPLOSS": 0.1577,
        "ID": "buy_one"
    },
    {
        "ADDRESS": "0x0ff6ffcfda92c53f615a4a75d982f399c989366b",
        "SYMBOL": "LAYER",
        "BUYPRICE": 0.30,
        "SELLPRICE": 0.50,
        "MAXTOKENS": 800,
        "BUYAMOUNT": 100,
        "STOPLOSS": 0.45,
        "ID": "buy_one"
    }
]

**Comment by CryptoGnome** [comment]
What is your discord name for reference

**Comment by edblak** [comment]
0.2647 ETH

**Comment by CryptoGnome** [comment]
yo need to fix your setting you were trying to buy more than you had in your wallet in eth

**Comment by edblak** [comment]
I calculated as follows.  0.2647 ETH at $360 USD is $95 USD.  WALT BUYPRICE is $0.044 * 1000 BUYAMOUNT = $44 USD. Similar logic for LAYER results in $30 USD.  So on these calculations the buy total ($74) is less than ETH value ($95). What is the issue?
