### ISSUE TITLE
Feature suggestion - support multiple wallets

### ISSUE THREAD

**Issue by cryptomius** [CryptoGnome/LimitSwap#304]
LimitSwap is great if you're trading all assets out of the same wallet, but we have segregated wallets for each asset and/or legal entity thus cannot be trading out of the same wallet. Also if we set up multiple instances of LimitSwap we get banned from the Ethereum node.
It would be great if LimitSwap supported multiple asset wallets in the tokens.json ❤

**Comment by CryptoGnome** [comment]
you can run more that one instance, you would need to run multiple VPS to do this

**Comment by cryptomius** [comment]
Yes running multiple VPS instances is a solution but it is also more costly, technically more complex, and unnecessary if the product were improved to handle multiple wallets.
