### ISSUE TITLE
would like to know where tokens.json is being used

### ISSUE THREAD

**Issue by flip456** [CryptoGnome/LimitSwap#312]
hi CryptoGnome, i messaged you on tg about this and you asked me to post it on github, this was the message:

hey @crypt0gnome i understand you're on vacation now so no rush for this 

i started using your limitswap bot pro version yesterday and just have to say that it is great! very quick and easy to use and  the wiki taught me everything i needed to know so thank you for all of that.

i just have one question, you mentioned in one of your videos that we can run multiple of the bots at the same time if we just copy and paste the file, which i did and got it working. 

my only issue with that is to update all the bots live i have to change the tokens.json file accross multiple bots which can take some time. most of the time i want all of the bots to run the same command at the same time. 

so my question is - what is the file that is using the tokens.json paramaters? if i knew this i think i may be able to replace it across multiple bots to just use one of the tokens.json file - that way i would only have to update that one file to have all the bots change instantly

thanks for your time and hope you enjoyed your vacation 😃

**Comment by flip456** [comment]
this isn't necessary now, i found a way to edit multiple files across different folders with one command

**Comment by alefantozzi** [comment]
I'm looking for the same thing. Have been using a batch file to copy, but doesn't seem to be the best solution. Which way are you using @flip456 ?
