### ISSUE TITLE
Error on selling token

### ISSUE THREAD

**Issue by hen0va** [CryptoGnome/LimitSwap#313]
Im using the LimitSwap v 3.22 and  Bot works fine on buying token but having an error on selling.

This is for Pancakeswap trades.

PreAuth was enabled, high gas and slippage as well.

Error Log : https://pastebin.com/s8mA2fRn
Token : https://pastebin.com/Amwt5vAA

**Comment by tende4** [comment]
Limitswap v3.22, v3.23
The purchase succeeded but stopped at the sell due to an error. 

v3.21 There is no error in the sell

Error log: https://pastebin.com/utLk9h1e
Token: https://pastebin.com/h2e7Pf9y

**Comment by CryptoGnome** [comment]
#319
