### ISSUE TITLE
bot price is not zhe realy price

### ISSUE THREAD

**Issue by tker90** [CryptoGnome/LimitSwap#314]
the bot price
![image](https://user-images.githubusercontent.com/64395375/127293017-5e9334bf-aaa2-4183-9277-a22cd4911c65.png)

the pancake price:
![image](https://user-images.githubusercontent.com/64395375/127293180-ad0a0254-5919-473c-8c44-1365a07eab38.png)

my token json:

[
  {
  "SYMBOL": "FAR",
  "ADDRESS": "0xa0ecaf5edf5df69edc7768da897dcea7d0c8e526",
  
  "USECUSTOMBASEPAIR": "true",
  "BASESYMBOL": "USDT",
  "BASEADDRESS": "0x55d398326f99059ff775485246999027b3197955",
  "BUYAMOUNTINBASE": "100",
  "BUYPRICEINBASE": "7.9",
  
  
  "SELLAMOUNTINTOKENS": "100",
  "SELLPRICEINBASE": "8.2",
  
  
  "MAXTOKENS": "100",
  "MOONBAG": "0",
  "SLIPPAGE": "10",
  "HASFEES": "true",
  "GAS": "5",
  "BOOSTPERCENT": "0",
  "GASLIMIT": "500000",
  
  
  "LIQUIDITYCHECK": "true",
  "LIQUIDITYAMOUNT": "10"
  }
]

**Comment by CryptoGnome** [comment]
are you sure the bot reads the price much faster than pancakeswap :D

**Comment by tker90** [comment]
The price difference is so big. Why did you tell me about the delay? Can the price be delayed for 3 days?

**Comment by phast184** [comment]
@tker90 I can see that the liquidity is kind of low. Could it be the reason for the price difference?

**Comment by CryptoGnome** [comment]
yes and our price is more accurate
