### ISSUE TITLE
Transaction shows error and got only 5% tokens

### ISSUE THREAD

**Issue by kiruthemes** [CryptoGnome/LimitSwap#317]
I tried the limitswap for the first time today. The transaction got executed but I see some error in the transaction. Some 5% tokens were sent to my wallet and 95% tokens were sent to another wallet. Could this be due to error or antibot mechanism? What must have caused the error in the transaction? Shall I share the tx for you to check?

![image](https://user-images.githubusercontent.com/57863409/127631144-0c1540e6-08d6-4711-8635-c59f3674c5a6.png)

**Comment by CryptoGnome** [comment]
yes this looks like antibot, you need to check contracts for weird things sometimes
