### ISSUE TITLE
Error Selling Token During Snipe

### ISSUE THREAD

**Issue by Ojay4real** [CryptoGnome/LimitSwap#319]
I was successfully able to buy into a token which was pre-approved, it found a sell signal but errored out.

Screenshot of the log attached.
<img width="428" alt="ddds" src="https://user-images.githubusercontent.com/59031515/127704785-db3bc8c2-d2cd-47a5-9e7d-ff72a70e4985.PNG">

**Comment by CryptoGnome** [comment]
Sending out fix today! Thank you for detailed reports!
