### ISSUE TITLE
SELLAMOUNTINTOKENS ALL bug

### ISSUE THREAD

**Issue by hen0va** [CryptoGnome/LimitSwap#321]
version : 3.23
When i put a value for SELLAMOUNTINTOKENS like 1 or any other number, its working.
If I put "ALL", it throws this error

Traceback (most recent call last):
  File "LimitSwap.py", line 1092, in run
  File "LimitSwap.py", line 740, in sell
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]
INFO: 2021-08-02 00:31:54,083 Restarting LimitSwap

**Comment by CryptoGnome** [comment]
#319
