### ISSUE TITLE
Bot used 70% slippage while i put 1%

### ISSUE THREAD

**Issue by H4nnelor** [CryptoGnome/LimitSwap#322]
so i just wanted to buy with 1% slippage, i got frontrunned and only got 30% of my investment. how is that even possible?????

https://bscscan.com/tx/0x13d38142dea41d8a6f5abd4369775093c435b2ae580021b175c31b26ccc1e199
https://bscscan.com/tx/0x4de01832e3123e4f9fcf02b100ec9515035e519ba6e88bd4b1ac66ec44440bbb

my tokens:

[
  {
  "SYMBOL": "DND",
  "ADDRESS": "0x14c358b573a4ce45364a3dbd84bbb4dae87af034",
  
  "USECUSTOMBASEPAIR": "true",
  "BASESYMBOL": "BUSD",
  "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
  "BUYAMOUNTINBASE": "10000",
  "BUYPRICEINBASE": "7.7",
  
  
  "SELLAMOUNTINTOKENS": "ALL",
  "SELLPRICEINBASE": "900",
  
  
  "MAXTOKENS": "5",
  "MOONBAG": "0",
  "SLIPPAGE": "1",
  "HASFEES": "false",
  "GAS": "35",
  "BOOSTPERCENT": "0",
  "GASLIMIT": "2500000",
  
  
  "LIQUIDITYCHECK": "false",
  "LIQUIDITYAMOUNT": "10"
  }
]

**Comment by CryptoGnome** [comment]
![image](https://user-images.githubusercontent.com/33667144/127861117-534b55b3-9c1e-4319-88d4-4f02c102cee0.png)

**Comment by CryptoGnome** [comment]
it looks like you routed through the BNB pair.
The bot always routes to WBNB for token to token swaps....

Not a slippage issue it is a liquidity issue. The best way to avoid this is only use the bot on pairs with BNB as a base pair

**Comment by Abide8** [comment]
I would love to know more about the difference between routing through a BNB and a WBNB pair. Can you share more on this please?
