### ISSUE TITLE
Matic ping pong

### ISSUE THREAD

**Issue by Carbastan** [CryptoGnome/LimitSwap#329]
I'm new here, so maybe is my mistake. I created an ping pong order on quickswap with custom pair true and maxtokens 1, so bot can only buy once! It's that the way? Bot doesn't stop, buys over and over again! I was looking to bsc- buy/sell Kpad with busd second example from wiki! It is possible to make it work on Matic so I can only buy one time and sell everything on my asking price? If the answer is yes, I would like to see an example on wiki one day!

**Comment by CryptoGnome** [comment]
ping pong no longer supported
