### ISSUE TITLE
Check approvals on base token

### ISSUE THREAD

**Issue by albertocastillo2001** [CryptoGnome/LimitSwap#330]
Hello

I had a buy order set to buy a token with USDT. Unfortunately LimitSwap didn't check if the base token was approved for trading, which lead it to burn a substantial ammount of eth on failed transactions. The error received by the uniswap contract was "Bad instruction". After some digging I found out it was because USDT was not approved.

**Comment by CryptoGnome** [comment]
Bot already does this if you use preapprove...

**Comment by albertocastillo2001** [comment]
Hi

No. My settings.json file has the preapprove setting to true. It didn't approve the base USDT pair. It spent a lot of money in fees because it didn't approve USDT.

Maybe it might preapprove it on restart, but not if you update the tokens.json file while it's running. So please check that.

**Comment by CryptoGnome** [comment]
check approvals on fail tx to make sure tokens are good

**Comment by CryptoGnome** [comment]
added check approvals on failed tx adding to next release, thank you for helping declare this a bug

```
tx = wait_for_tx(tx, token['ADDRESS'], True)
if tx != 1:
    preapprove(tokens)
else:
    pass
```
