### ISSUE TITLE
Bot used direct route even if "LIQUIDITYINNATIVETOKEN": "true"

### ISSUE THREAD

**Issue by tsarbuig** [CryptoGnome/LimitSwap#342]
hi,
a user reported me that this configuration resulted in this Tx : https://bscscan.com/tx/0x251e5f86911cce374e8167f8989ee1ac861edb98cca96f6aadae36acbead707b

Shouldn't the bot has used the BUSD > WBNB > Token token, instead if direct route, here ?

It resulted in fund loss for him

Thanks

[
  {
   
  "ENABLED": "TRUE",
  "SYMBOL": "HERO",
  "ADDRESS": "0xe8176d414560cfe1bf82fd73b986823b89e4f545",

  "USECUSTOMBASEPAIR": "true",
  "BASESYMBOL": "BUSD",
  "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
  "LIQUIDITYINNATIVETOKEN": "true",
  "BUYAMOUNTINBASE": "1000",
  "BUYPRICEINBASE": "2.6",

  "SELLAMOUNTINTOKENS": "ALL",
  "SELLPRICEINBASE": "2.8",

  "MAXTOKENS": "100",
  "MOONBAG": "0",
  "SLIPPAGE": "1",
  "HASFEES": "false",
  "GAS": "5",
  "BOOSTPERCENT": "0",
  "GASLIMIT": "1000000",

  "LIQUIDITYCHECK": "false",
  "LIQUIDITYAMOUNT": "10000000000000"

  }
]

**Comment by CryptoGnome** [comment]
fixed in next release, this is because he used lowercase, true bot now checks for this

**Comment by alefantozzi** [comment]
same happened for me yesterday, is it solved?

**Comment by alefantozzi** [comment]
can u check @CryptoGnome

**Comment by CryptoGnome** [comment]
new release will be out today
