### ISSUE TITLE
Liquidity in BUSD only failing

### ISSUE THREAD

**Issue by Abide8** [CryptoGnome/LimitSwap#343]
For token 0x0a95a36655424c46db3aaef0776961049da722d1, liquidity was provided in BUSD with no liquidity in BNB. See at https://poocoin.app/tokens/0x0a95a36655424c46db3aaef0776961049da722d1

In trying to use LimitSwap, I'm getting the following error when trying to trade tokens ...
" RHINO-BUSD  Not Listed For Trade Yet... waiting for liquidity to be added on exchange"

![image](https://user-images.githubusercontent.com/90096837/132094902-23d01e6f-3e9a-4c3a-8f8d-391c339695fd.png)

Here's my setting.json

        "USECUSTOMNODE": "false",
        "CUSTOMNODE": "put your own node here if you want and make, USECUSTOMNODE = TRUE",
        "EXCHANGE": "pancakeswap",
    "EXCHANGEVERSION": "2",
    "PREAPPROVE": "true",
    "UNLIMITEDSLIPPAGE": "false"
    }
]

Here's my tokens.json
```
  "ENABLED": "true",

  "SYMBOL": "RHINO-BUSD",
  "ADDRESS": "0x0a95a36655424c46db3aaef0776961049da722d1",
  "BUYAMOUNTINBASE": "200",
  "BUYPRICEINBASE":  "0.00025",
  "SELLPRICEINBASE": "0.00035",
  "SLIPPAGE": "20",

  "MAXTOKENS": "102",
  "MOONBAG": "101",

  "LIQUIDITYCHECK": "false",
  "LIQUIDITYAMOUNT": "30000",
  "LIQUIDITYINNATIVETOKEN": "false",
  "USECUSTOMBASEPAIR": "true",
  "BASESYMBOL": "BUSD",
  "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",
 
  "SELLAMOUNTINTOKENS": "ALL",
  "HASFEES": "true",
  "GAS": "6",
  "BOOSTPERCENT": "20",
  "GASLIMIT": "500000"

  }
```

Here's the error.log...

> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "LimitSwap.py", line 1181, in run
>   File "LimitSwap.py", line 1023, in sell
>   File "web3\contract.py", line 957, in call
>   File "web3\contract.py", line 1501, in call_contract_function
>   File "web3\module.py", line 57, in caller
>   File "web3\manager.py", line 187, in request_blocking
>   File "web3\manager.py", line 167, in formatted_response
>   File "web3\manager.py", line 67, in apply_error_formatters
>   File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
>   File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
>   File "web3\_utils\method_formatters.py", line 566, in raise_solidity_error_on_revert
> web3.exceptions.ContractLogicError: execution reverted: PancakeLibrary: INSUFFICIENT_INPUT_AMOUNT
> 
> 

Here's the exception.log....

> Traceback (most recent call last):
>   File "LimitSwap.py", line 1181, in run
>   File "LimitSwap.py", line 1023, in sell
>   File "web3\contract.py", line 957, in call
>   File "web3\contract.py", line 1501, in call_contract_function
>   File "web3\module.py", line 57, in caller
>   File "web3\manager.py", line 187, in request_blocking
>   File "web3\manager.py", line 167, in formatted_response
>   File "web3\manager.py", line 67, in apply_error_formatters
>   File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
>   File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
>   File "web3\_utils\method_formatters.py", line 566, in raise_solidity_error_on_revert
> web3.exceptions.ContractLogicError: execution reverted: PancakeLibrary: INSUFFICIENT_INPUT_AMOUNT

**Comment by CryptoGnome** [comment]
fixing in 3.31
