### ISSUE TITLE
Display different prices

### ISSUE THREAD

**Issue by lamthao232** [CryptoGnome/LimitSwap#344]
Limit swap V3.3 display price issue.
- Limit swap: 0.187$
- Poocoin, pancakesawp: 0.171
<img width="1350" alt="Price difference" src="https://user-images.githubusercontent.com/39077280/132135278-b28994f1-db04-42f0-a7fb-917e97bc27f0.PNG">
<img width="390" alt="Price difference 02" src="https://user-images.githubusercontent.com/39077280/132135293-83c6beb3-1253-4e19-b313-d4b5948afd99.PNG">

- Limit swap: 0.88$
- Pancake: 0.97$
<img width="1154" alt="Price v2" src="https://user-images.githubusercontent.com/39077280/132152139-94cfa928-ee71-43ad-a4a3-5c70b6fd5840.PNG">

When setting "Liquidity native token" = true. Price is correct. But this token only use Busd pair liquidity.
<img width="211" alt="liqui" src="https://user-images.githubusercontent.com/39077280/132152317-cf1cb7a2-cf85-4dad-861d-a13068ec146a.PNG">

How can we solve that problem?
Thank you!

**Comment by CryptoGnome** [comment]
this should be fixed in 3.31 please reopen if you see this again
