### ISSUE TITLE
Prevent bot from buying if price impact is too high

### ISSUE THREAD

**Issue by tsarbuig** [CryptoGnome/LimitSwap#346]
Hi,
As we said on Telegram, it would be nice if the bot was able to detect if price impact isn't too high before buying, to prevent users lose money if they route through a route with low liquidity

My ideas : 
- calculate price impact, and don't buy if it's > 25%

- or maybe easier : check the amount of $$ in the liquidity routes that the bot is about to use, and don't buy if liquidity < 1000$

**Comment by CryptoGnome** [comment]
users can use liquidity check option for this
