### ISSUE TITLE
Liquidity reserves gone wrong

### ISSUE THREAD

**Issue by markblouin** [CryptoGnome/LimitSwap#348]
Okay so a token i invested in is named sugar ada and I use liquidity check = true to scan the price so the bot could buy. So I put the liquidity that it shows on poocoin and it does not go through. Then, on the python of limitswap it shows that the liquidity reserve is only 15bnb bnb meanwhile it is 135 bnb on poocoin. It is weird because the more buys come in, it goes even lower in the python. Here is the address of the token: 0x97701fb92ffa37a29766514dc3b7838430a7f39c.

**Comment by CryptoGnome** [comment]
Fixed in 3.32 Release
