### ISSUE TITLE
PREAPPROVE approves token every time you start the bot

### ISSUE THREAD

**Issue by tsarbuig** [CryptoGnome/LimitSwap#352]
https://t.me/LimitSwap/80627

this user (an old one, with good skills) reported that when having preapprove set to True, but is approving tokens each time i restart bot, even 10x

His tokens.json : 

[
  {

    "ENABLED": "true",

    "SYMBOL": "XCT_Citadel_one",
    "ADDRESS": "0xe8670901e86818745b28c8b30b17986958fce8cc",
    "BUYAMOUNTINBASE": "0",
    "BUYPRICEINBASE":  "0",
    "SELLPRICEINBASE": "0.1",
    "SLIPPAGE": "1",

    "MAXTOKENS": "0",
    "MOONBAG": "0",

    "LIQUIDITYCHECK": "true",
    "LIQUIDITYAMOUNT": "30000",
    "LIQUIDITYINNATIVETOKEN": "false",
    "USECUSTOMBASEPAIR": "true",
    "BASESYMBOL": "USDT",
    "BASEADDRESS": "0x55d398326f99059ff775485246999027b3197955",

    "SELLAMOUNTINTOKENS": "ALL",
    "HASFEES": "false",
    "GAS": "11",
    "BOOSTPERCENT": "20",
    "GASLIMIT": "250000"

  },
  {

    "ENABLED": "true",

    "SYMBOL": "2CRZ",
    "ADDRESS": "0x3a6e8b36645d6c252714daddd28ec0673535a109",
    "BUYAMOUNTINBASE": "0",
    "BUYPRICEINBASE":  "0",
    "SELLPRICEINBASE": "0.033",
    "SLIPPAGE": "1",

    "MAXTOKENS": "0",
    "MOONBAG": "0",

    "LIQUIDITYCHECK": "false",
    "LIQUIDITYAMOUNT": "30000",
    "LIQUIDITYINNATIVETOKEN": "false",
    "USECUSTOMBASEPAIR": "true",
    "BASESYMBOL": "BUSD",
    "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",

    "SELLAMOUNTINTOKENS": "ALL",
    "HASFEES": "false",
    "GAS": "11",
    "BOOSTPERCENT": "20",
    "GASLIMIT": "250000"

  }
]

check the result on BSCan : https://bscscan.com/address/0x36a1387e88037caa653d2eb572b3c7603984a470

**Comment by CryptoGnome** [comment]
fixed
