### ISSUE TITLE
LIQUIDITYAMOUNT still don't work with last version

### ISSUE THREAD

**Issue by tsarbuig** [CryptoGnome/LimitSwap#353]
- token : https://poocoin.app/tokens/0xe8670901e86818745b28c8b30b17986958fce8cc

Pc v2 | XCT/USDT LP Holdings:
205,248.09 USDT ($205,071) | Chart | Holders
Pc v2 | XCT/BNB LP Holdings:
0.64 BNB ($246) | Chart | Holders
Pc v2 | XCT/BUSD LP Holdings:
0.43 BUSD ($0) | Chart | Holders

- but bot output is:

2021-09-20 09:13:56.524753 Current Wallet Balance is: 0.0 XCT_Citadel_one
2021-09-20 09:13:56.970064 Current Liquidity Reserves: 4.60002421393e-07 USDT
2021-09-20 09:13:56.980831 Not enough Liquidity for XCT_Citadel_one

- user suggestion : 
token has 6 decimals
so might be issue with that

- tokens.json : 
"ENABLED": "true",

    "SYMBOL": "XCT_Citadel_one",
    "ADDRESS": "0xe8670901e86818745b28c8b30b17986958fce8cc",
    "BUYAMOUNTINBASE": "0.1",
    "BUYPRICEINBASE":  "0.5",
    "SELLPRICEINBASE": "0.5",
    "SLIPPAGE": "1",

    "MAXTOKENS": "0.01",
    "MOONBAG": "0",

    "LIQUIDITYCHECK": "true",
    "LIQUIDITYAMOUNT": "40000",
    "LIQUIDITYINNATIVETOKEN": "false",
    "USECUSTOMBASEPAIR": "true",
    "BASESYMBOL": "USDT",
    "BASEADDRESS": "0x55d398326f99059ff775485246999027b3197955",

    "SELLAMOUNTINTOKENS": "ALL",
    "HASFEES": "false",
    "GAS": "5",
    "BOOSTPERCENT": "20",
    "GASLIMIT": "250000"

**Comment by CryptoGnome** [comment]
they creator made the pair USDT/XCT no real way of telling this in the code, as it works correctly when done  normally
