### ISSUE TITLE
Bot used direct route even if "LIQUIDITYINNATIVETOKEN": "true" 

### ISSUE THREAD

**Issue by tsarbuig** [CryptoGnome/LimitSwap#356]
look, there is an issue in newset version still
3.32

tokens.json
[
  {

    "ENABLED": "true",

    "SYMBOL": "MONI_Monsta_Infinite",
    "ADDRESS": "0x9573c88ae3e37508f87649f87c4dd5373c9f31e0",
    "BUYAMOUNTINBASE": "1",
    "BUYPRICEINBASE":  "3",
    "SELLPRICEINBASE": "222",
    "SLIPPAGE": "1",

    "MAXTOKENS": "0.1",
    "MOONBAG": "0",

    "LIQUIDITYCHECK": "true",
    "LIQUIDITYAMOUNT": "50",
    "LIQUIDITYINNATIVETOKEN": "true",
    "USECUSTOMBASEPAIR": "true",
    "BASESYMBOL": "BUSD",
    "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",

    "SELLAMOUNTINTOKENS": "ALL",
    "HASFEES": "false",
    "GAS": "5",
    "BOOSTPERCENT": "20",
    "GASLIMIT": "250000"

  }
]

according to wiki, if     "LIQUIDITYINNATIVETOKEN": "true",  it should route through WBNB before trading into Moni, so it should go BUSD -> WBNB -> MONI

however, it did not, check screen below, direct route was executed, liquidity there is tiny so if executed with normal order size you get rekt with price impact

![telegram-cloud-photo-size-4-5931420015997860197-y](https://user-images.githubusercontent.com/70858574/134232543-d9a34673-4e7b-4536-a455-e19a74b2cd33.jpg)

------------------------

however, when i reverse transaction and this time i sell, it works ok, it goes through MONI -> WBNB -> BUSD pool 
[
  {

    "ENABLED": "true",

    "SYMBOL": "MONI_Monsta_Infinite",
    "ADDRESS": "0x9573c88ae3e37508f87649f87c4dd5373c9f31e0",
    "BUYAMOUNTINBASE": "0",
    "BUYPRICEINBASE":  "0",
    "SELLPRICEINBASE": "1",
    "SLIPPAGE": "1",

    "MAXTOKENS": "0",
    "MOONBAG": "0",

    "LIQUIDITYCHECK": "true",
    "LIQUIDITYAMOUNT": "50",
    "LIQUIDITYINNATIVETOKEN": "true",
    "USECUSTOMBASEPAIR": "true",
    "BASESYMBOL": "BUSD",
    "BASEADDRESS": "0xe9e7cea3dedca5984780bafc599bd69add087d56",

    "SELLAMOUNTINTOKENS": "ALL",
    "HASFEES": "false",
    "GAS": "5",
    "BOOSTPERCENT": "20",
    "GASLIMIT": "250000"

  }
]

![telegram-cloud-photo-size-4-5931420015997860198-y](https://user-images.githubusercontent.com/70858574/134232593-16c192cd-8eb4-4295-83ff-f785a13f8ed7.jpg)

so the conclusion is:

    "LIQUIDITYINNATIVETOKEN": "true",
works only for selling token, not buying.
IF buying, only direct route is executed, if selling, it goes through wbnb

**Comment by CryptoGnome** [comment]
fixed next release
