### ISSUE TITLE
wrong price

### ISSUE THREAD

**Issue by Alexander0003** [CryptoGnome/LimitSwap#357]
![Untitled1](https://user-images.githubusercontent.com/91158134/134240733-79d94a75-faf7-4a27-a7e5-a72e6fe553b8.png)
![Untitled2](https://user-images.githubusercontent.com/91158134/134240736-71dc4abd-e6f2-4d4e-aa77-3ca2c61f9502.png)
![Untitled3](https://user-images.githubusercontent.com/91158134/134240741-e4eb6a3b-f3ac-40d4-a367-5ad2b5713f64.png)

**Comment by zalypkinkakylik** [comment]
have the same problem gives me wrong value compare to poocoin if I use BUSD 
![image](https://user-images.githubusercontent.com/91197761/134343284-32c93a9a-d841-4434-a4fe-cb6b1be52574.png)

**Comment by Alexander0003** [comment]
super
thks
and, you do a good job
Go ahead! 

Sent from Mail for Windows

**Comment by Alexander0003** [comment]
![Untitled](https://user-images.githubusercontent.com/91158134/134987937-823920f8-1659-4282-b612-9cdc2fac6cf9.png)
![Untitled2](https://user-images.githubusercontent.com/91158134/134988155-905dcb25-644a-4aa1-a3a2-3356ffb924ea.png)


doesn't work
