### ISSUE TITLE
LOST MONEY - should have stopped considering slipage

### ISSUE THREAD

**Issue by alefantozzi** [CryptoGnome/LimitSwap#358]
today I had bot configured to use 30% slipage but I received only . WHAT HAPPENDED?

I sold 4,762.66657904 tokens
Sell Signal Found @0.000587409627842720 so I should receive between 1.958345342 and 2.797636203 BNB. Actual amount I receive was 0.00245419203908718 BNB!!!!  

UNLIMETEDSLIPAGE was false

here tx
https://bscscan.com/tx/0xebad46c7a642f390ff54461dbbf9b42557708f8a9e941f01788e8d5fc224fce6

log
FO: 2021-09-23 14:13:15,824 Current Tokens Staked = 100.00136563223884
INFO: 2021-09-23 14:13:15,824 YOUR BOT IS CURRENTLY RUNNING VERSION 3.3
INFO: 2021-09-23 14:13:16,011 Checking Latest Release Version on Github, Please Make Sure You are Staying Updated = v3.32
INFO: 2021-09-23 14:30:44,831 Sell Signal Found @0.000587409627842720

here is my settings/tokens config:
 {
  "ENABLED": "TRUE",
  "SYMBOL": "HER",
  "ADDRESS": "0x6B9F6f911384886b2e622e406327085238F8A3C5",
  "USECUSTOMBASEPAIR": "FALSE",
  "BASESYMBOL": "DEFAULT-BSC",
  "BASEADDRESS": "",
  "LIQUIDITYINNATIVETOKEN": "TRUE",

  "BUYAMOUNTINBASE": "0.1",
  "BUYPRICEINBASE": "0",

  "SELLAMOUNTINTOKENS": "ALL",
  "SELLPRICEINBASE": "0.0003235635",

  "MAXTOKENS": "100",
  "MOONBAG": "4000",

  "SLIPPAGE": "30",
  "HASFEES": "FALSE",
  "GAS": "20",
  "BOOSTPERCENT": "0",
  "GASLIMIT": "500000",

  "LIQUIDITYCHECK": "FALSE",
  "LIQUIDITYAMOUNT": "0"
  }

        "EXCHANGE": "pancakeswap",
		"EXCHANGEVERSION": "2",
		"PREAPPROVE": "true",
		"UNLIMITEDSLIPPAGE": "false"

**Comment by CryptoGnome** [comment]
you routed through BNB when liquidity is in BUSD
![image](https://user-images.githubusercontent.com/33667144/134934484-7929cf18-e8b5-49f6-b2f5-4683d7fd9b40.png)
