### ISSUE TITLE
Issue with "SELLAMOUNTINTOKENS"

### ISSUE THREAD

**Issue by tsarbuig** [CryptoGnome/LimitSwap#360]
When SELLAMOUNTINTOKENS is different from ALL, lots of users have issues.

For instance : 

- tokens.json : 
[
  {

    "ENABLED": "true",

    "SYMBOL": "ekart",
    "ADDRESS": "0xd2e1cd904d1903c3746fa4bdf02e3dcd01c4548c",
    "BUYAMOUNTINBASE": "0.0",
    "BUYPRICEINBASE":  "0.0",
    "SELLPRICEINBASE": "0.000000018176610433",
    "SLIPPAGE": "15",

    "MAXTOKENS": "3000000",
    "MOONBAG": "3000000",

    "LIQUIDITYCHECK": "false",
    "LIQUIDITYAMOUNT": "0.001",
    "LIQUIDITYINNATIVETOKEN": "false",
    "USECUSTOMBASEPAIR": "false",
    "BASESYMBOL": "MATIC",
    "BASEADDRESS": "0x7D1AfA7B718fb893dB30A3aBc0Cfc608AaCfeBB0",

    "SELLAMOUNTINTOKENS": "100000.0",
    "HASFEES": "true",
    "GAS": "6",
    "BOOSTPERCENT": "20",
    "GASLIMIT": "1500000"

  }
]

- will terminate with this error : 
Could not identify the intended function with name getAmountsOut, positional argument(s) of type (<class 'int'>, <class 'list'>) and keyword argument(s) of type {}.
Found 1 function(s) with the name getAmountsOut: ['getAmountsOut(uint256,address[])']
Function invocation failed due to no matching argument types.
Traceback (most recent call last):
  File "LimitSwap.py", line 1181, in run
  File "LimitSwap.py", line 830, in sell
  File "web3\contract.py", line 876, in call
  File "web3\contract.py", line 881, in _set_function_info
  File "web3\_utils\contracts.py", line 163, in find_matching_fn_abi
web3.exceptions.ValidationError: 
Could not identify the intended function with name getAmountsOut, positional argument(s) of type (<class 'int'>, <class 'list'>) and keyword argument(s) of type {}.
Found 1 function(s) with the name getAmountsOut: ['getAmountsOut(uint256,address[])']
Function invocation failed due to no matching argument types.

**Comment by CryptoGnome** [comment]
fixing in next release
