### ISSUE TITLE
Please add TraderJoe exchange (Avalanche)

### ISSUE THREAD

**Issue by c133** [CryptoGnome/LimitSwap#367]
Hi Gnome, could you please consider adding trader joe swap. Many new coins are showing up there instead of Pangolin. Thanks!

**Comment by Zerusi** [comment]
@c133 https://github.com/eSwapping/ESWAP-Limit-Order-Bot/releases/ check that bot :)

**Comment by CryptoGnome** [comment]
adding 3.36
