### ISSUE TITLE
Option To Disable/Delay Auto-Approve - Limit Trader

### ISSUE THREAD

**Issue by eazyEE-create** [CryptoGnome/LimitSwap#39]
When first time purchase are made with new tokens, the bot will process an **approve transaction** before actually purchasing the token. If you could make an option to disable or delay this until after the token is purchased. This would allow for quicker purchases with more of the low-cap/Volatile tokens. 

Would it be possible to add a toggle/option to prevent this from happening?

**Comment by sidework** [comment]
For the record, options are always great, but I would never turn this option on. There are contracts out there that are scams that are written to only approve for the token owner. UNI will let you buy it, and then when you go to sell, it fails because you cant approve it. I would rather be safe than sorry. Maybe it would make more sense to approve it right away when adding the pair for trading, regardless of buying/selling at the moment? I would turn that on... :)

**Comment by CryptoGnome** [comment]
yea in some ways I agree, you can go to uniswap and approve manually if you are that concerned

**Comment by eazyEE-create** [comment]
> For the record, options are always great, but I would never turn this option on. There are contracts out there that are scams that are written to only approve for the token owner. UNI will let you buy it, and then when you go to sell, it fails because you cant approve it. I would rather be safe than sorry. Maybe it would make more sense to approve it right away when adding the pair for trading, regardless of buying/selling at the moment? I would turn that on... :)

I agree 100%, but leave it up to the user to decide this. It's a nice safety feature.

**Comment by eazyEE-create** [comment]
> yea in some ways I agree, you can go to uniswap and approve manually if you are that concerned
> We will keep this open for debate and see what others say

Were you planning on implementing this on the next update?

**Comment by jondoeog** [comment]
I would really love to see that feature on. I use bot mostly to trade coins that I know or when I want to snipe something fast, having approve before buy kind of ruin the play.

Definitely choice for user would be great!

**Comment by pasil11** [comment]
I think this option would be appreciated (as you wrote we can approve manually in UNI or etherscan)

**Comment by eazyEE-create** [comment]
> I think this option would be appreciated (as you wrote we can approve manually in UNI or etherscan)

Yeah you can manually if the token is live and trading, but if there's no liquidity you can't because you need the pair address

**Comment by jondoeog** [comment]
Any ETA when it might get implemented?
