### ISSUE TITLE
[ERROR]HASFEES

### ISSUE THREAD

**Issue by Tranq93** [CryptoGnome/LimitSwap#48]
Tried to sell a token when the price was above the sell signal.
The bot tried to sell the token but it threw up an error.
Error log has been attached.
[errors.log](https://github.com/CryptoGnome/LimitSwap/files/5505757/errors.log)

**Comment by sidework** [comment]
I also got this today:
INFO: 2020-11-08 10:29:28,713 | Current Ticker LUCKY: $ 3524.912079 | Buy Price: 1500 | Take Profit: 3500 | Stop Loss: Not Enabled
INFO: 2020-11-08 10:29:28,715 SELL SIGNAL FOUND
INFO: 2020-11-08 10:29:29,194 SELLINGLUCKY
ERROR: 2020-11-08 10:29:29,194 'HASFEES'
Traceback (most recent call last):
  File "limitswap.py", line 486, in start_bot
  File "limitswap.py", line 443, in start_many
  File "limitswap.py", line 170, in limit_orders
  File "limitswap.py", line 363, in sell
KeyError: 'HASFEES'

**Comment by CryptoGnome** [comment]
this will be resolved in next version
