### ISSUE TITLE
[Feature Request] Buy/Sell based on % of current price

### ISSUE THREAD

**Issue by kobiek** [CryptoGnome/LimitSwap#49]
Please add this feature where the bot buy and sell based on whatever the current price target is.  Essentially make it flow with the price movement kind of like how UNDB does it. 

Example : X token is current priced at 100, and I set a 10% buy/sell order. It will buy the moment it hits 90 and sell the moment it hits 110.  It will then use whatever the current price is, say its 105, and set a 10% buy/sell order based on that.

**Comment by CryptoGnome** [comment]
this will be a different bot, releasing soon
