### ISSUE TITLE
Check liquidity pool of coin before trading

### ISSUE THREAD

**Issue by jondoeog** [CryptoGnome/LimitSwap#60]
Add price impact setting, similar to slippage setting so bot would not execute trade if above certain % price impact.

Why?

Let's say we trade token and high percentage of liquidity gets removed. With low liquidity high volatility is possible (which can trigger sell/buy orders) and price impacts of 80%+ are possible.
In such a case, price may surge (so we sell) or tank (so we buy) but when we execute trade we automatically loose 80% of investment.

**Comment by CryptoGnome** [comment]
This is already implemented and called slippage.

**Comment by jondoeog** [comment]
No it is not.

Price impact and slippage are separate things. I always thought the same and I have checked it myself! I can even show you tx and chart of a token where it happened.

For instance if you want to buy:
TokenA for ETH.
The rate is 1000 for Token A with price impact 1%
Now if you want to buy 10 000 token A price impact will be 10%
Below in GUI you can see how much tokens you will receive.

Now the slippage controls deviation from this displayed numer!

So it is possible to have price impact of 10%, and slippage 1% and trade will go through.

If you don't believe me, just go yourself on uni app and find some not liquid token. Do small trade there, for instance you get price impact 1%. Set your slippage to 0.1% and you will see that trade will be executed.

**Comment by CryptoGnome** [comment]
Can you send me a coin that you see this on so I can look please?

**Comment by jondoeog** [comment]
done privately.

**Comment by CryptoGnome** [comment]
What bot is this request for?

**Comment by jondoeog** [comment]
I guess both, Limitswap and Ping Pong.
