### ISSUE TITLE
[Feature request] : Stop Loss with additional settings

### ISSUE THREAD

**Issue by kobiek** [CryptoGnome/LimitSwap#64]
Make it so if the stop loss function is called, another set of gas/gas limit/slippage settings are used.  For example I trade with 100 gas boost., 250k limit limit, and 2% slippage normally, but when stop loss is called, I want it to use 500 gas boost, 300k limit, and 10% slip as an example.

Essentially trying to minimize the odds of the tx failing.

**Comment by CryptoGnome** [comment]
This is to complex for most users, and would a hindrance to the UI IMO, will leave open for upvotes or comments for 30 days

**Comment by jondoeog** [comment]
Limit is irrelevant, but custom slippage for buy and sell would be nice. Buying with low slippage is a must to avoid getting frontrun, while this is not a problem while selling as there are no bots front running sells (for now). some tokens have burn and require higher slippage so it would be good to be able to separate it. I think I saw an issue where someone was mentioning about moving slippage into token .json (and separate it for buy/sell would be nice)
