### ISSUE TITLE
"One time" or "until turned off" trade button

### ISSUE THREAD

**Issue by jondoeog** [CryptoGnome/LimitSwap#66]
Add ability to set if the trade should be executed once or until disabled. What does it mean?

Let's assume I want to buy EXAMPLE1 token when it gets down to 10$ (current price is 15$) and sell when it bounces 20% so at 12$:
BUY:  10$
SELL: 12$
current price 15$

So it's a flash crash bid on a strong support, that even if this token start downtrend, at least once it should bounce off that 10$ mark giving 20% profit and later it can go lower.

Currently bot would buy at 10$, then sell at 12$ and if price reverses bot would try to buy again at 10$ and sell at 12$ and over and over again but at some point this bounce may not occur (or it can happen only once, with each test of support it gets weaker and weaker).

It's ok when we are able to manually switch off that trade, once it's executed so bot will not try to purchase again..However if it happens while we sleep or travel etc. we would get rekt.

Having an option that certain token position is only executed once, would help to fix that. I hope I explained it clearly. In case of any further explanation being needed, contact me on discord PM or ask below.

**Comment by CryptoGnome** [comment]
Just lower the max buy to just over 1$ or 0.000001 ETH

**Comment by jondoeog** [comment]
Lol, but the idea is, it happens when you are AFK and can't touch bot and change settings.

Currently it will do trades over and over.
