### ISSUE TITLE
Successful Sell trade cancel/disable the remaining buy order

### ISSUE THREAD

**Issue by jondoeog** [CryptoGnome/LimitSwap#67]
Currently we have 20k of example coins.

BUY: 10$
SELL: 20$
CURRENT PRICE: 15$
AMOUNT: 17k
MAX: 30k
MOON: 0

**now we have 2 possible scenarios:**

**1)** Price goes 15$-> 20$ -> 10$ (We reach our sell target first followed by a dump)
Bot will do:    SELL all coins at 20$ -> buy 2x 17k at 10$

**2)** Price goes 15$ -> 10$ (flash crash) -> 20$ 
Bot will do:   BUY 17k coins at 10$ -> sell all coins at 20$, repeat 2x17k buy if it drops to 10$

Let me explain thinking and the scenarios now.

Assume we are trading token that has uptrend and we want to sell our tokens at 20$. We think that it may have a flash crash that's why we set order way below current price to accumulate more. Token doesn't execute flash crash and goes to 20$, limitswap sells the token and we booked profit. In such a case the price of 10$ might be never revisited unless something bad happens with project and it would most likely result in a bad trade and limitswap would buy 2x17k instead of 1x 17k as we don't have the coins that were sold first. (we need to have MAX setting on 30k if we want to buy additional 17k coins in an event of flash crash to get total of ~34k coins)

If we are afk or sleeping etc. we are unable to switch off bot so the option to automatically disable trading pair after successful sell is made, would be great addition! [to protect from scenario **1)** ]

However we would like to still have sell trade active after flash crash to sell even more coins at 20$ mark [scenario **2)** ]

In case of any further explanation being needed, contact me on discord PM or ask below.

**Comment by CryptoGnome** [comment]
stop loss achieves this, after a pair is stopped out it will no longer trade till you remove that pair from the stopped pairs logs
