### ISSUE TITLE
Limitswap GUI: error issue

### ISSUE THREAD

**Issue by seekerp** [CryptoGnome/LimitSwap#71]
random error (5 out of 10 times error) 
upon clicking on the individual token clone or edit selection, the popup dialog will have empty data. I have to position mouse cursor on the word 'edit' or 'clone' in order for the data to be populated. 
This only happen on limiswap dashboard.

browser: chrome Version 87.0.4280.66 (Official Build) (64-bit)
sys: win10

image circled is the area that i need to click in order for the existing data to be intact.
![2020-11-26-(3)](https://user-images.githubusercontent.com/1462884/100333997-2d24e480-300e-11eb-9c49-8acbd0ecbd3d.png)

**Comment by koyabya** [comment]
I confirm that there is such a problem. I will check what can be done with it. Thanks for the screen :)

**Comment by koyabya** [comment]
Problem resolved. Will be added to new release.
