### ISSUE TITLE
Restart limitswap/ping ong bot in case of internet outgage

### ISSUE THREAD

**Issue by jondoeog** [CryptoGnome/LimitSwap#74]
Whenever our VPS has drop in internet connection bot stops operating. (limitswap.exe)

- in order to reproduce it -> Try running limitswap/pingpong bot, disconnect internet (unplug network cable etc) and connect it back. You will see that bot can't handle it. You have to manually restart it.

possible way to fix it:
Maybe once user press start button, there is some monitoring to see if limitswap.exe is running..If for some reason it stops, it is automatically restarted (other than user manually pressing stop button or closing the window).

**Comment by CryptoGnome** [comment]
I need the error that is printed to catch this then i can fix

**Comment by jondoeog** [comment]
There is no error, just a hole in long.. Check discord other people are reporting the same

**Comment by CryptoGnome** [comment]
In progress
