### ISSUE TITLE
Incorrect BASE token price

### ISSUE THREAD

**Issue by indigo16** [CryptoGnome/LimitSwap#75]
Hey  guys, maybe the price of BASE Token 0x07150e919B4De5fD6a63DE1F9384828396f25fDC is not correct in in limitbot? 
It is a 9 decimals Token
![image](https://user-images.githubusercontent.com/71349616/101017127-f6991d80-3569-11eb-8470-dd825edd323a.png)
![image](https://user-images.githubusercontent.com/71349616/101017153-00228580-356a-11eb-8f72-81491fd56d38.png)

**Comment by CryptoGnome** [comment]
Base has no ABI on etherscan hence not tradeable, they need to make it public
