### ISSUE TITLE
The function 'balanceOf' was not found in this contract's abi.

### ISSUE THREAD

**Issue by Crypto22h** [CryptoGnome/LimitSwap#76]
Trying to trade BASE token and I get this issue when I try to start trading:

> Authorizing User ....
> Current Tokens Staked =  25.1
> Casual Price =  10  Tokens Staked
> Trader Price =  25  Tokens Staked
> Welcome Pro User!
> Calling Many
> Current Ticker BASE : $ 743898.299572 | Buy Price .5 | Take Profit: .6 | Stop Loss: Not Enabled
> SELL SIGNAL FOUND
> Check Error Log, Found an Uncommon Exception, Please make a github issue showing full log.
> Traceback (most recent call last):
>   File "limitswap.py", line 618, in start_bot
>   File "limitswap.py", line 571, in start_many
>   File "limitswap.py", line 212, in limit_orders
>   File "limitswap.py", line 393, in sell
>   File "limitswap.py", line 82, in check_balance
>   File "web3\contract.py", line 193, in __getattr__
> web3.exceptions.ABIFunctionNotFound: ("The function 'balanceOf' was not found in this contract's abi. ", 'Are you sure you provided the correct contract abi?')
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "limitswap.py", line 750, in <module>
>   File "limitswap.py", line 713, in start_bot
> TypeError: can only concatenate str (not "ABIFunctionNotFound") to str
> [9380] Failed to execute script limitswap

Token: 0x07150e919b4de5fd6a63de1f9384828396f25fdc

**Comment by CryptoGnome** [comment]
Base has No ABI on etherscan hence it is not botable
