### ISSUE TITLE
Limit Bot throwing error when sell signal found, but no tokens held.

### ISSUE THREAD

**Issue by jared-ddm** [CryptoGnome/LimitSwap#78]
Connected to Blockchain2 = True
Authorizing User ....
Current Tokens Staked =  25.0
Casual Price =  10  Tokens Staked
Trader Price =  25  Tokens Staked
Welcome Pro User!
Calling Many
Current Ticker AAVE : $ 92.280345 | Buy Price 72 | Take Profit: 90 | Stop Loss: Not Enabled
SELL SIGNAL FOUND
Check Error Log, Found an Uncommon Exception, Please make a github issue showing full log.
Traceback (most recent call last):
  File "limitswap.py", line 618, in start_bot
  File "limitswap.py", line 571, in start_many
  File "limitswap.py", line 212, in limit_orders
  File "limitswap.py", line 393, in sell
  File "limitswap.py", line 82, in check_balance
  File "web3\contract.py", line 193, in __getattr__
web3.exceptions.ABIFunctionNotFound: ("The function 'balanceOf' was not found in this contract's abi. ", 'Are you sure you provided the correct contract abi?')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "limitswap.py", line 750, in <module>
  File "limitswap.py", line 713, in start_bot
TypeError: can only concatenate str (not "ABIFunctionNotFound") to str
[3608] Failed to execute script limitswap

**Comment by CryptoGnome** [comment]
For some reason AAVE does not have a public ABI so we cannot read your wallet balance of that coin
https://etherscan.io/token/0x7fc66500c84a76ad7e9c93437bfc5ac33e2ddae9#readContract

**Comment by jondoeog** [comment]
@CryptoGnome

But can you see that at least his current price is displayed correctly?

Regarding other issue with Base
https://etherscan.io/token/0x07150e919b4de5fd6a63de1f9384828396f25fdc

it also doesn't have ABI shared but price was inncorrect.
The difference between Base and AAVE is 9 vs 18 decimals.

Why it matters?

If we will want to trade 9 decimals coin that have ABI, most likely tracked price will be wrong.
