### ISSUE TITLE
Limitswap bot ignores '"GASLIMIT" setting

### ISSUE THREAD

**Issue by jondoeog** [CryptoGnome/LimitSwap#80]
I was trading some complicated contract token with fees which had high gas limit usage.

I've set 
"GASLIMIT": "500000",

and got failed tx 'out of gas' and I saw that bot tried to use only 300 000
I guess it's hardcoded.

I did made sure it's saved as I checked .JSON file and settings after it executed and it was 500 000 there.

**Comment by CryptoGnome** [comment]
can you please confirm this, after reviewing code it still does not make sense that you are getting this

**Comment by jondoeog** [comment]
It's quite costly to reproduce it. When it happens again I'll let you know.
