### ISSUE TITLE
[LimitSwap - feature request] % range from buy/sell target

### ISSUE THREAD

**Issue by kobiek** [CryptoGnome/LimitSwap#81]
Some of my sales are having a hard time hitting the exact target. Can we have it so that we can set an acceptable % range from our buy/sell target that the bot can execute from?

ex: Sell target is 100.  If I set an acceptable threshold of 5% it will sell at 95, 96, 97, 98 instead of waiting for exactly 100.

**Comment by jondoeog** [comment]
So just lower the sell but amount you want a threshold ? :)

**Comment by kobiek** [comment]
> So just lower the sell by amount you want a threshold ? :)

We could walk too but built cars for convenience. This is just that, a nice feature to have!

**Comment by jondoeog** [comment]
But this is redundant man, waste of time and complicating code for no reason.

**Comment by kobiek** [comment]
> But this is redundant man, waste of time and complicating code for no reason.

Think you misunderstood. I'm talking about the acceptable price target range and not the quantity of tokens. This would make automated trading much easier than guessing an exact price point.

**Comment by jondoeog** [comment]
You don't understand me.
None of the exchange have it, why would bot want to have it?

It's really doesn't make any sense to me.

Let's say you want to sell something when it hit price of 100$...but you want to specify a range of 95-100$. So in this case when 95$ gets reached it will sell. So what is a logical difference in selling at 95$?

In programmers word:
Trade will be executed at 95$, regardless how you set a sell order. If by 95$ directly or at 95-100$ range, it will be sold at 95$ :)

When some whale buy and price surge to 120$ and you have order set at 100$, it will still sell at 120$ as 100$<120$ and order will be executed at market price.

**Comment by kobiek** [comment]
The logical difference is that you could miss that price target by a few
dollars or cents by placing an exact value. Why wouldn't you want to
optimize for gains?

If the dev feels this will add value to his product and differentiate
himself from other "exchange", he can do it. If not its another suggestion
he can reject.

**Comment by CryptoGnome** [comment]
this is not something we can predict, we can se price and send order. What happens after that from a competition standpoint is up to the market. quick tip use more gas boost to beat other sellers.
