### ISSUE TITLE
Feature Request: LimitSwap Token Wallet lookup

### ISSUE THREAD

**Issue by sidework** [CryptoGnome/LimitSwap#85]
I would like to set up the PingPong bot with a different wallet so those funds/activities don't get mixed with other things going on in my main wallet, but I don't want to have to have another 50 LIMIT. It would be nice if we could specify what wallet has the LIMIT, and what wallet the bot should use.

**Comment by CryptoGnome** [comment]
This is not possible with the token structure, you need to use separate wallets to run multiple bots.
