### ISSUE TITLE
Looking for a Simple "Buy Once" Option

### ISSUE THREAD

**Issue by thefalcon424** [CryptoGnome/LimitSwap#86]
Most of my trades are only looking for one entry point and one sell point that I don't want to have to actively monitor due to trading other pairs, or being afk/sleeping.

If I have an buy at $100, and then a sell at $150, then I consider this a success and I want that particular Id to stop trading. There is a scenario where after the sell, I have made my profit, but the coin crashes and burns and on the way down, the bot decides to pick up another trade for a huge loss.

Currently I have to monitor the bot so that once the trade is executed, I have to manually adjust the settings and trade actively, only using the bot to make sure the trade is executed quickly.

I'm looking for either a toggle that enables only buying once, or a value which i can put how many times a buy is authorized (i would set to 1) for that particular Id

**Comment by jondoeog** [comment]
I second that, was mentioning it in one of my issues raised some time ago

**Comment by CryptoGnome** [comment]
This is already possible with both bots using max amounts.

**Comment by jondoeog** [comment]
Can you explain how?

It will just keep trading back and forth.

Current price is 1.5$ and you have 0 tokens, 80 set as max, set buy of 100 tokens and 0 moonbag
If you have buy set at 1$ and sell at 2$

1) If price goes to 1$ it will buy 100 tokens. If price goes to 2$ it will sell 100 tokens. If price crash after reaching 2$ to 1$ and keeps dumping, bot will buy again at 1$...How you can stop that from happening in your opinion?
