### ISSUE TITLE
Limitswap retry failed tx due to slippage "insufficient output amount" when retryonfail set to 0

### ISSUE THREAD

**Issue by jondoeog** [CryptoGnome/LimitSwap#89]
I use Limitswap bot
Had retryonfail set to 0
usemany on
2 token pair in tokens.json

Supprisingly bot failed 1st TX due to slippage and send another one, which was also slightly above set price. (maybe it didn't check before sending again?)

v. 2.84

**I have suspicion that maybe 0 in _retryonfail_ works like in liquidity check? 0 means unlimited amount of retry?**

**Comment by CryptoGnome** [comment]
Please update to latest verison...

**Comment by CryptoGnome** [comment]
And keep me posted if this continues

**Comment by jondoeog** [comment]
I updated and it still happened. I had 0 retryonfail   and limitswap bot bought 3x...I got rug pulled because of that and lost 0.4 ETH :(

first 2 tx failed (as low slippage was preventing that) but 3rd transaction went through)

Please fix that.

**Comment by CryptoGnome** [comment]
Found Bug and fixed
