### ISSUE TITLE
Not enough liquidity to make this trade despite value set being much lower than actual pool

### ISSUE THREAD

**Issue by jondoeog** [CryptoGnome/LimitSwap#95]
![image](https://user-images.githubusercontent.com/74243437/102823171-af6cb280-43da-11eb-83a7-395a9c900056.png)
![image](https://user-images.githubusercontent.com/74243437/102823196-c90dfa00-43da-11eb-95a8-32956d392847.png)
![image](https://user-images.githubusercontent.com/74243437/102823230-d75c1600-43da-11eb-9218-2311df0a0bf0.png)

Screens are self explanatory. Coin has 300 ETH in a pool, I have set 50 in settings yet getting error about not enough.
Maybe something to do with token being 9 decimals? (0xe17f017475a709de58e976081eb916081ff4c9d5)

**Comment by CryptoGnome** [comment]
#96
