### ISSUE TITLE
Not an issue but feature requests as per discord link

### ISSUE THREAD

**Issue by JaapS6** [CryptoGnome/LimitSwap#97]
Essentially make it work like a conventional limit order function on a CEX:

in particular, I'd like to:

1) easily set a stop loss without putting some stuff into the bot to make it think I used it to buy with, when I didn't. Info on how to do this is hard to find and really it would be good to not have to do it at all.

2) set a stop loss with an actual price rather than a percentage.

3) move a stop loss up to lock in profit

WRT 1 in particular but to the bot in general, basic instructions on how to use it are hard to find. They should be easily available and simple and you shouldn't have to ask in social media channels on how to do stuff. 

IMO the ping pong and the other features should be secondary to the limit order functions. As you get more complicated you're appealing to a smaller proportion of users and therefore there will be less demand for the bot. Get the limit order core functions to work better and explain them clearly and you'll get more users.

**Comment by CryptoGnome** [comment]
Trail Stop is not in planned features.
