### ISSUE TITLE
Coins with sell fee feature

### ISSUE THREAD

**Issue by jondoeog** [CryptoGnome/LimitSwap#99]
As explained on discord,

RSI/ITS etc. forks have tax (2.5-10% or sometimes more) with each transaction (buy/sell) and some % of it gets redistributed to all holders, including myself.

Example:
I have 1887 of X coin
moonbag 500
after sale
I have 503.997

If after the sale, price goes to my sell price, it will trigger sale again for 3.997 coins in above example.

It will be basically infinite loop of sells each time price crosses sell price. It can be a costly mistake as such coins usually have high gas limit usage due to complicated nature of contracts (a lot of interactions). Transaction with 100 gwei can cost between 30-60$, depending how creative was owner of coin. If someone doesn't think about it and is AFK...he may drain his whole account to 0.

**Comment by CryptoGnome** [comment]
added
